### ISSUE TITLE
`Non-zero status code returned while running MatMul node` once too many requests

### ISSUE THREAD

**Issue by JulesBelveze** [microsoft/onnxruntime#10343]
**Describe the bug**
Hey all,
I am running some inferences with FastAPI & ONNX-runtime on GPU and I am currently trying to benchmark for autoscaling. For this reason the payload I'm sending is always the same.
Everything seems to work fine but once I make too many simultaneous requests I'm getting the following issue:
```
E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running MatMul node. Name:'MatMul_33' Status Message: CUBLAS error executing cublasGemmHelper( Base::CublasHandle(), transB, transA, static_cast<int>(helper.N()), static_cast<int>(helper.M()), static_cast<int>(helper.K()), &alpha, reinterpret_cast<const CudaT*>(right_X->template Data<T>()), ldb, reinterpret_cast<const CudaT*>(left_X->template Data<T>()), lda, &zero, reinterpret_cast<CudaT*>(Y->template MutableData<T>()), ldc, device_prop)
```

I ain't really clear to me, but I suspect this is an OOM issue, right?
The main problem is that once the above error is hit then it is no longer possible to make a call to the API without getting this error, as if the entire `InferenceSession` was down.

I know that's a quite vague description but that's all I have, feel free if you need any further info. I can provide checkpoints and payload if needed.

**Urgency**
This is quite blocking as the entire `InferenceSession` seems to be down and needs to be restarted.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux #1 SMP x86_64 Intel(R) Xeon(R) CPU @ 2.00GHz GenuineIntel GNU/Linux`
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: onnxruntime-gpu==1.10.0
- Python version: Python 3.8.10
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA Version: 11.0
- GPU model and memory: Tesla P4

**Expected behavior**
I would expect the session to be still running.

**Comment by edgchen1** [comment]
Can you please provide a minimal reproducible example program and model?

**Comment by wszgrcy** [comment]
same error  
```
Non-zero status code returned while running MatMul node. Name:'/encoder/layer.0/intermediate/dense/MatMul' Status Message: : Error: Non-zero status code returned while running MatMul node. Name:'/encoder/layer.0/intermediate/dense/MatMul' Status Message: 
    at Immediate.<anonymous> (c:\code\my-project\shenghuabi\dist\node_modules\onnxruntime-node\dist\backend.js:45:108)
    at process.processImmediate (node:internal/timers:478:21)
```

**Comment by wszgrcy** [comment]
I found the problem. It seems to be caused by a sudden overflow of memory, not a gradual increase, but a sudden increase
![image](https://github.com/user-attachments/assets/dad14237-5f83-4e4e-b7aa-f325f2b501a5)
![image](https://github.com/user-attachments/assets/d8613daa-def7-400e-91cf-725493c51233)
Continuous call for about 5 minutes. Suddenly increased memory usage was observed, followed by a crash
I discovered it through recording a video replay. The increase speed is extremely fast

**Comment by wszgrcy** [comment]
> This issue has been automatically marked as stale due to inactivity and will be closed in 7 days if no further activity occurs. If further support is needed, please provide an update and/or more details.

Please recheck this issue

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
