### ISSUE TITLE
GPU build broken with CUDA SDK 12.0

### ISSUE THREAD

**Issue by tufei** [microsoft/onnxruntime#13932]
### Describe the issue

It seems the ORT has a hard dependency on CUDA SDK 11.x?

[dnn_onnxruntime @ 0x3f7ccc0] SessionOptionsAppendExecutionProvider_CUDA(): /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1069 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

### To reproduce

On Fedora 36 update to latest CUDA SDK 12.0 then try some examples.

### Platform

Linux

### OS Version

Fedora 36

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.0

**Comment by snnn** [comment]
If your system doesn't have libcublasLt.so.11, then the answer is : "yes".

**Comment by tufei** [comment]
Thanks, I meant to say, is it possible that in your future releases, not link to libcublasLt.so.11, but only libcublasLt.so, and then check versions using proper API calls?

Regards,

**Comment by snnn** [comment]
@tufei, would you mind showing me an example? We didn't explicitly put the name of "libcublasLt.so.11" in the link command. We put "-lcublasLt" there and linker resolved it to "libcublasLt.so.11". Most Linux shared libs work in such a way. I don't know how to change it.

**Comment by tufei** [comment]
https://stackoverflow.com/questions/12637841/what-is-the-soname-option-for-building-shared-libraries-for

**Comment by smartnet-club** [comment]
terminate called after throwing an instance of 'Ort::Exception'
  what():  /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1069 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

ldd libonnxruntime_providers_cuda.so
	libcublasLt.so.11 => not found
	libcublas.so.11 => not found

**Comment by borisfom** [comment]
@tufei : You should be able to install CUDA 11 libraries alongside with your CUDA 12 to work around.
@snnn : it would be nice to have a separate onnxruntime-gpu wheel built with CUDA 12 available. Is that in your nearest plans ?

**Comment by dzhao** [comment]
coask when onnx can support cuda12? or even support building CUDA 12?

**Comment by zeruniverse** [comment]
I think https://github.com/microsoft/onnxruntime/pull/14659 needs to be merged into latest release for CUDA 12 build fix

**Comment by chriskyndrid** [comment]
+1

For the time being, I resolved this as follows:

1) Add the fc35 cuda repo:
```bash
sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64/cuda-fedora35.repo
sudo dnf clean all
```

If you're using the[ RPM fusion repositories ](https://rpmfusion.org/Howto/CUDA)for your display drivers:
```bash
sudo dnf module disable nvidia-driver 
```

2) Install CUDA 11.8
```bash
sudo dnf install cuda-11-8
```

3) cuDNN
You may/will need to make sure you have the appropriate libcudnn8 installed for the version of cuda you are using:

```bash
sudo dnf install https://developer.download.nvidia.com/compute/machine-learning/repos/rhel8/x86_64/nvidia-machine-learning-repo-rhel8-1.0.0-1.x86_64.rpm
```

and e.g.

```bash
sudo dnf install libcudnn8 libcudnn8-devel libnccl libnccl-devel
```

You can browse the packages from the rhel8 repo [here](https://developer.download.nvidia.com/compute/machine-learning/repos/rhel8/x86_64/)

After the above I can successfully run inference. I'm using the ort crate for rust with models I converted from pytorch(mostly) to ONNX.

**Comment by snnn** [comment]
> @snnn : it would be nice to have a separate onnxruntime-gpu wheel built with CUDA 12 available. Is that in your nearest plans ?

Right now each our package only works with a specific CUDA minor version. For example, the last one only works with CUDA 11.6 and the next one will only work with CUDA 11.8.  At some point it will become CUDA 12 point something.  If you have more questions about the project's future plan, you can ask @pranavsharma .

**Comment by AkshayUpadhye** [comment]
I also had a similar issue, building onnxruntime from source helped !!

**Comment by snnn** [comment]
The last code should works fine on Windows with CUDA 12.2. I am adding a build pipeline for it. #17231

**Comment by wongwenxin** [comment]
I had a similar problem when using Clion to compile the onnxruntime-cpp example in yolov8！！


[DCSP_ONNX]:/onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1131 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

But I can find **libcublasLt.so.11** under **/usr/local/cuda11.8/lib64**

Please help！！！

**Comment by snnn** [comment]
@wongwenxin  See https://man7.org/linux/man-pages/man8/ld.so.8.html about how Linux finds dynamic libraries. You might need to run ldconfig to add the directory to the operating system's database, or setup LD_LIBRARY_PATH env. 

I will close this issue now because it is as designed. All our prebuilt packages were built with CUDA 11.x. They are not compatible with CUDA 12.x.  However, you can build ONNX Runtime from source with CUDA 12.x if you need to use that version of CUDA. 

Feel free to open a new issue if you hit any build error with that.

**Comment by jrabek** [comment]
Has anyone built the onnx runtime with cuda 12.x successfully? What would be the best instructions to use to do so?

**Comment by snnn** [comment]
The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu

**Comment by jrabek** [comment]
Thank you for the comment and link @snnn! Much appreciated 🙏

**Comment by FrancescoSaverioZuppichini** [comment]
> The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu

having this error

<img width="737" alt="Screenshot 2023-12-24 at 16 25 48" src="https://github.com/microsoft/onnxruntime/assets/15908060/afe684d5-9fa2-41b7-9743-d2d0a8798919">


thank you so much

**Comment by FrancescoSaverioZuppichini** [comment]
Tried with 

```

pip install ort-nightly-gpu
```

working!

**Comment by vladoossss** [comment]
> The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu
Tried this:
```
pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
```

But saw this error:

ERROR: Could not find a version that satisfies the requirement ort-nightly-gpu==1.17.0.dev20231205004 (from versions: none)
ERROR: No matching distribution found for ort-nightly-gpu==1.17.0.dev20231205004

**Comment by FrancescoSaverioZuppichini** [comment]
> > The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu
> 
> Tried this:
> 
> ```
> pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
> ```
> 
> But saw this error:
> 
> ERROR: Could not find a version that satisfies the requirement ort-nightly-gpu==1.17.0.dev20231205004 (from versions: none) ERROR: No matching distribution found for ort-nightly-gpu==1.17.0.dev20231205004

look at my message above, try with

```
pip install ort-nightly-gpu
```

**Comment by vladoossss** [comment]
> > > The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu
> > 
> > 
> > Tried this:
> > ```
> > pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But saw this error:
> > ERROR: Could not find a version that satisfies the requirement ort-nightly-gpu==1.17.0.dev20231205004 (from versions: none) ERROR: No matching distribution found for ort-nightly-gpu==1.17.0.dev20231205004
> 
> look at my message above, try with
> 
> ```
> pip install ort-nightly-gpu
> ```

With this command you installed ort-nightly-gpu==1.15.dev
But this version will not work with CUDA 12.

**Comment by FrancescoSaverioZuppichini** [comment]
> > > > The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu
> > > 
> > > 
> > > Tried this:
> > > ```
> > > pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But saw this error:
> > > ERROR: Could not find a version that satisfies the requirement ort-nightly-gpu==1.17.0.dev20231205004 (from versions: none) ERROR: No matching distribution found for ort-nightly-gpu==1.17.0.dev20231205004
> > 
> > 
> > look at my message above, try with
> > ```
> > pip install ort-nightly-gpu
> > ```
> 
> With this command you installed ort-nightly-gpu==1.15.dev But this version will not work with CUDA 12.

I have CUDA 12 and it works 🤔

**Comment by RoM4iK** [comment]
For people who will come after me, you can download whl here
https://dev.azure.com/onnxruntime/onnxruntime/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview/1.17.0

**Comment by arcayi** [comment]
> > > > > The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu
> > > > 
> > > > 
> > > > Tried this:
> > > > ```
> > > > pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > But saw this error:
> > > > ERROR: Could not find a version that satisfies the requirement ort-nightly-gpu==1.17.0.dev20231205004 (from versions: none) ERROR: No matching distribution found for ort-nightly-gpu==1.17.0.dev20231205004
> > > 
> > > 
> > > look at my message above, try with
> > > ```
> > > pip install ort-nightly-gpu
> > > ```
> > 
> > 
> > With this command you installed ort-nightly-gpu==1.15.dev But this version will not work with CUDA 12.
> 
> I have CUDA 12 and it works 🤔

this works. thanks

**Comment by burgalon** [comment]
for some reason i'm using `FROM nvidia/cuda:12.2.0-base-ubuntu22.04` docker and have `onnxruntime-gpu==1.17.0` but still getting error on not finding `libcublasLt.so.11` as if CUDA detection is going wrong. 
Thank you for your help!

**Comment by ZhangHangjianMA** [comment]
> > > > > > The latest code should work fine with CUDA 12.2. And we have a nightly package for it. https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu
> > > > > 
> > > > > 
> > > > > Tried this:
> > > > > ```
> > > > > pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > But saw this error:
> > > > > ERROR: Could not find a version that satisfies the requirement ort-nightly-gpu==1.17.0.dev20231205004 (from versions: none) ERROR: No matching distribution found for ort-nightly-gpu==1.17.0.dev20231205004
> > > > 
> > > > 
> > > > look at my message above, try with
> > > > ```
> > > > pip install ort-nightly-gpu
> > > > ```
> > > 
> > > 
> > > With this command you installed ort-nightly-gpu==1.15.dev But this version will not work with CUDA 12.
> > 
> > 
> > I have CUDA 12 and it works 🤔
> 
> this works. thanks

I follow the solution: https://github.com/Fannovel16/comfyui_controlnet_aux/issues/75#issuecomment-1880314874, it works for me, but with a warning:  onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.

**Comment by xenova** [comment]
Has anyone got this working with `onnxruntime-gpu==1.18.0`? (https://pypi.org/project/onnxruntime-gpu/1.18.0/)

**Comment by meikuam** [comment]
> Has anyone got this working with `onnxruntime-gpu==1.18.0`? (https://pypi.org/project/onnxruntime-gpu/1.18.0/)

I m facing same issue too. Seems like its not fixed at newer version of package.

**Comment by nigh8w0lf** [comment]
> > Has anyone got this working with `onnxruntime-gpu==1.18.0`? (https://pypi.org/project/onnxruntime-gpu/1.18.0/)
> 
> I m facing same issue too. Seems like its not fixed at newer version of package.

Are you trying to Improve your Hallo Inference as well?
Looks like they skipped 1.18 nightly wheels, went from 17 to 19

**Comment by geraldstanje** [comment]
i see the same:
https://github.com/onnx/sklearn-onnx/issues/1111

**Comment by snnn** [comment]
Did you get the package from https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple/ ?

**Comment by geraldstanje** [comment]
@snnn thanks for quick reply! no from: https://pypi.org/project/onnxruntime-gpu/ - so fetch it from the link and all should be good?

**Comment by snnn** [comment]
Sorry I gave you the wrong URL. The URL  should be 
```
https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

**Comment by geraldstanje** [comment]
> Sorry I gave you the wrong URL. The URL should be
> 
> ```
> https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> ```

whats the diff between the 2 different URLs? does new URL have onnxruntime-gpu==1.18.0?

also what is ort-nightly-gpu?

**Comment by meikuam** [comment]
> Sorry I gave you the wrong URL. The URL should be
> 
> ```
> https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> ```

Thanks that helped to fix this problem for now

**Comment by snnn** [comment]
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12 is the place where we host our CUDA 12 python, nuget and maven packages. You can click the "Connect to feed" button to see instructions.

https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly is similar to above, but it only hosts nightly packages, and currently it doesn't have nightly packages for python. (We are working on it).

**Comment by shivshankar11** [comment]
for late comer:
here's the way to enable gpu accelerate on cuda12.x

track the issue here for version changes: https://github.com/microsoft/onnxruntime/issues/13932
runtime nightly: https://dev.azure.com/onnxruntime/onnxruntime/_artifacts/feed/onnxruntime-cuda-12
ort nightly:https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly

#with cu12.*
pip install coloredlogs flatbuffers numpy packaging protobuf sympy
pip install ort-nightly-gpu --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
pip install onnxruntime-gpu==1.17.0 --index-url=https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple/

**Comment by uladzislau-varabei** [comment]
Thanks a lot @shivshankar11. Can confirm that when installed with PyTorch 2.3 with CUDA 12 from Conda it works. I would say that just installing onnxruntime-gpu is fine if you have everything before. So it should be only like this:
`pip install onnxruntime-gpu==1.17.0 --index-url=https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple/`
