### ISSUE TITLE
Can't deploy ONNX model in CPU only environment

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1424]
**Describe the bug**
ONNX Runtime failed to create session on environment that doesn't have GPUs, even only the default execution provider is used (thus should not require any CUDA devices). The error is the following:
```
/workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 100: no CUDA-capable device is detected ; GPU=-726270608 ; hostname=97f47b644c57 ; expr=cudaStreamCreateWithFlags(&streams_[kCudaStreamCopyIn], cudaStreamNonBlocking); 
Stacktrace:

Stacktrace:
```

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source from master
- ONNX Runtime version: 0.4.0
- Python version: 3.5.2
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: CUDA 10, CUDNN 7
- GPU model and memory: TITAN V (not exposed to ONNX Runtime by running in `docker` instead of `nvidia-docker`)

**To Reproduce**
build the following sample code and try to run in environment that doesn't have GPUs.

1.  `docker run -it --rm onnx-runtime` (image that builds ONNX Runtime)
2. `gcc -std=c++11 c_api_sample.cc -o ort_c_api -lonnxruntime -lstdc++`
3. `./ort_c_api`

<details><summary>sample code</summary><p>

```C++
void CreateSession(
  const char* model_path, const int device_id, OrtEnv* env,
  OrtSessionOptions* session_options, OrtSession** session)
{
  // To deploy on different device, need to set provider on cloned option
  // as you can remove a execution provider once it is appended
  OrtSessionOptions* context_options;
  CHECK_STATUS(OrtCloneSessionOptions(session_options, &context_options));
  std::unique_ptr<OrtSessionOptions, decltype(&OrtReleaseSessionOptions)>
      options_wrapper(context_options, OrtReleaseSessionOptions);

  // Use CUDA, device 0. CPU if -1
  if (device_id >= 0) {
    CHECK_STATUS(OrtSessionOptionsAppendExecutionProvider_CUDA(context_options, device_id));
    std::cout << "deploy on GPU " << device_id << std::endl;
  } else {
    std::cout << "deploy on CPU" << std::endl;
  }
  
  CHECK_STATUS(OrtCreateSession(env, model_path, context_options, session));
}

int
main(int argc, char* argv[])
{
  //===================== Factory Scope ======================
  // initialize  enviroment...one enviroment per process
  // enviroment maintains thread pools and other state info
  
  // [TODO] look into OrtCreateEnvWithCustomLogger()
  OrtEnv* env;
  CHECK_STATUS(OrtCreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env));
  std::unique_ptr<OrtEnv, decltype(&OrtReleaseEnv)>
        env_wrapper(env, OrtReleaseEnv);

  //===================== Backend Scope ======================
  // session option is backend-wise as it also specified GPU device
  // but other session option can be set "globally", like const variables
  // defined in factory object and use it to set corresponding options
  // initialize session options if needed
  OrtSessionOptions* session_options;
  CHECK_STATUS(OrtCreateSessionOptions(&session_options));
  std::unique_ptr<OrtSessionOptions, decltype(&OrtReleaseSessionOptions)>
        options_wrapper(session_options, OrtReleaseSessionOptions);
  CHECK_STATUS(OrtSetSessionThreadPoolSize(session_options, 1));

  // disable graph optimization
  CHECK_STATUS(OrtSetSessionGraphOptimizationLevel(session_options, 0));

  //===================== Context Scope ======================
  // create multiple sessions and load models into memory
  std::vector<std::pair<const char*, int>> model_spec;
  {
    model_spec.emplace_back("onnx_float32_float32_float32/1/model.onnx", -1);
  }

  std::vector<std::unique_ptr<OrtSession, decltype(&OrtReleaseSession)>> sessions;
  for (const auto path_device : model_spec) {
    OrtSession* session;
    CreateSession(
        path_device.first, path_device.second, env, session_options, &session);
    sessions.emplace_back(session, OrtReleaseSession);
  }

  //===================== Infer Scope ======================
  // for (auto& session_wrapper : sessions) {
  //   auto session = session_wrapper.get();
  //   //*************************************************************************
  //   // print model input/output layer (node names, types, shape etc.)
  //   std::cout << "Input infos:" << std::endl;
  //   auto input_tensors = GetIOTensors(session, true);

  //   std::cout << "Output infos:" << std::endl;
  //   auto output_tensors = GetIOTensors(session, false);

  //   // [TODO] fill data and run inference
  // }

  // Factory-wise
  
  return 0;
}
```
</p></details>

**Expected behavior**
Expect to create session successfully and print input / output tensor info (this part is omitted in the provided sample code):
```
root@70f031d8634f:/workspace# ./ort_c_api 
deploy on CPU
Input infos:
Number of tensors = 2
Tensor 0:
    name: INPUT0
    type: 1
    dims: [8,16]
Tensor 1:
    name: INPUT1
    type: 1
    dims: [8,16]
Output infos:
Number of tensors = 2
Tensor 0:
    name: OUTPUT0
    type: 1
    dims: [8,16]
Tensor 1:
    name: OUTPUT1
    type: 1
    dims: [8,16]

```

**Additional context**
The master commit that can produce expected behavior is 2f698bd54b713bb87dbd0bbb913e94bcf7fd480c (I didn't track down since which commit it is no longer producing expected behavior)
The latest master will produce the error message mentioned above.

**Comment by jywu-msft** [comment]
is this related to https://github.com/microsoft/onnxruntime/issues/1409 ? 
@HectorSVC

**Comment by HectorSVC** [comment]
Yes, it's duplicate.
For now, we don't support running a GPU python package on CPU only machine. You need to install the CPU package.

**Comment by GuanLuo** [comment]
@HectorSVC Thanks for the reply, but I am using the C API. Or is that true that even for C API, ONNX Runtime has to build **without** GPU support to be able to be used on CPU-only machine?

I know that at least in the current release, ONNX Runtime with GPU support can be run on CPU-only machine, is that unintended?

**Comment by HectorSVC** [comment]
you get the package from our official release right? no build it from our latest master, right? We fixed some issues relate to this recently. The should be the reason.
Ideally, user should be able to run model on CPU only device with a GPU package using C API.

**Comment by GuanLuo** [comment]
I see. I saw the fix for this issue and I will try that and see if that resolves the issue. Thanks.

**Comment by GuanLuo** [comment]
Yep, that resolved the issue. Thanks.
