### ISSUE TITLE
[Build] Build for CUDA failed at 52% and 56% on Ubuntu CUDA 10.2

### ISSUE THREAD

**Issue by junwang-wish** [microsoft/onnxruntime#14415]
### Describe the issue

Build for CUDA failed at 52% and 56% with CUDA 10.2

### Target platform

Ubuntu 18.04

### Build script

`./build.sh --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda`

### Error / output

```
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc.o
In file included from /workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.h:6:0,
                 from /workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc:3:
/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc: In member function ‘void onnxruntime::CudaNotification::wait_on_device(onnxruntime::Stream&)’:
/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc:28:47: error: too few arguments to function ‘cudaError_t cudaStreamWaitEvent(cudaStream_t, cudaEvent_t, unsigned int)’
                                         event_));
                                               ^
/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc:27:5: note: in expansion of macro ‘CUDA_CALL_THROW’
     CUDA_CALL_THROW(cudaStreamWaitEvent(static_cast<cudaStream_t>(device_stream.GetHandle()),
     ^~~~~~~~~~~~~~~
In file included from /usr/local/cuda/targets/x86_64-linux/include/channel_descriptor.h:61:0,
                 from /usr/local/cuda/targets/x86_64-linux/include/cuda_runtime.h:95,
                 from /workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_pch.h:12,
                 from /workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.h:4,
                 from /workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc:3:
/usr/local/cuda/targets/x86_64-linux/include/cuda_runtime_api.h:2289:58: note: declared here
 extern __host__ __cudart_builtin__ cudaError_t CUDARTAPI cudaStreamWaitEvent(cudaStream_t stream, cudaEvent_t event, unsigned int flags);
                                                          ^~~~~~~~~~~~~~~~~~~
CMakeFiles/onnxruntime_providers_cuda.dir/build.make:257: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc.o] Error 1
CMakeFiles/Makefile2:1912: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/tools/ci_build/build.py", line 2732, in <module>
    sys.exit(main())
  File "/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/tools/ci_build/build.py", line 2629, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/tools/ci_build/build.py", line 1395, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/tools/ci_build/build.py", line 764, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/opt/conda/envs/py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/conda/envs/py38/bin/cmake', '--build', '/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.
root@

### Visual Studio Version

_No response_

### GCC / Compiler Version

_No response_

**Comment by fs-eire** [comment]
Which CUDA version do you use?

**Comment by junwang-wish** [comment]
@fs-eire I am using CUDA 10.2 from within `nvcr.io/nvidia/pytorch:20.03-py3` dev container

**Comment by junwang-wish** [comment]
```
root@b2374e1cb5b2:/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime# nvidia-smi
Wed Jan 25 01:39:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.183      Driver Version: 384.183      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   37C    P0    56W / 300W |    881MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

root@b2374e1cb5b2:/workspaces/multitask-llm-rnd/coeus_inference/onnxruntime# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by fs-eire** [comment]
the 3rd parameter of function `cudaStreamWaitEvent()` is optional in [latest CUDA API](https://docs.nvidia.com/cuda/archive/11.8.0/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g7840e3984799941a61839de40413d1d9) but it's required in [v10.2](https://docs.nvidia.com/cuda/archive/10.2/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g7840e3984799941a61839de40413d1d9). 

@junwang-wish Could you help me to quickly check if it works to update line 27 in file onnxruntime\core\providers\cuda\cuda_stream_handle.cc

```cpp
    CUDA_CALL_THROW(cudaStreamWaitEvent(static_cast<cudaStream_t>(device_stream.GetHandle()),
                                        event_));
```

to

```cpp
    CUDA_CALL_THROW(cudaStreamWaitEvent(static_cast<cudaStream_t>(device_stream.GetHandle()),
                                        event_,
                                        0));
```

**Comment by junwang-wish** [comment]
Yep I changed it like you asked, waiting for the build, it normally takes > 30 minutes @fs-eire

**Comment by fs-eire** [comment]
you can try appending flag `--parallel` in the build command
```
   --parallel [PARALLEL]
                        Use parallel build. The optional value specifies the maximum number of parallel jobs. If the
                        optional value is 0 or unspecified, it is interpreted as the number of CPUs.
```

**Comment by junwang-wish** [comment]
Unfortunately, it is nor failing at 56%. @fs-eire you want to move this to another thread or continue here?
```
[ 56%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/tmp/onnxruntime/onnxruntime/core/providers/shared_library/provider_ort_api_init.cc.o
[ 56%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/tmp/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMakeFiles/onnxruntime_providers_cuda.dir/build.make:1335: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/tmp/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/tmp/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o] Error 1
CMakeFiles/Makefile2:1912: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/tmp/onnxruntime/tools/ci_build/build.py", line 2732, in <module>
    sys.exit(main())
  File "/tmp/onnxruntime/tools/ci_build/build.py", line 2629, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/tmp/onnxruntime/tools/ci_build/build.py", line 1395, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/tmp/onnxruntime/tools/ci_build/build.py", line 764, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/tmp/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/opt/conda/envs/py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/conda/envs/py38/bin/cmake', '--build', '/tmp/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.
```

**Comment by junwang-wish** [comment]
Found related [link](https://forums.developer.nvidia.com/t/solved-nvcc-fatal-a-single-input-file-is-required-for-a-non-link-phase-when-an-outputfile-is-s/37807/4) but not sure how to apply the fix to here

**Comment by fs-eire** [comment]
I am not sure if the link is related, and I don't have a Linux devbox right now to reproduce the issue.

**Comment by junwang-wish** [comment]
@fs-eire Thanks, is there a stable version of onnxruntime-gpu that has been verified to work with CUDA 10.2 on Ubuntu?

**Comment by pranavsharma** [comment]
We don't support 10.2. We've moved on to 11.x for a while now.

**Comment by fs-eire** [comment]
Those documents should be updated: https://onnxruntime.ai/docs/build/eps.html#notes

**Comment by junwang-wish** [comment]
Thanks @pranavsharma and @fs-eire i will close this issue then

**Comment by natke** [comment]
Related to #14417

**Comment by snnn** [comment]
> "nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified" 

When you see this, please go the the build folder and run "make VERBOSE=1", and find the failed nvcc command. Usually, it is because the command has  an extra parameter that nvcc wrongly thinks the extra parameter is a file name.   That's why it says "A single input file is required ". So, without seeing what the full command line, we can't know what went wrong. And, as @pranavsharma said above, we don't support CUDA 10.2 anymore. So very likely the error was because we were using a new parameter that the old CUDA version didn't recognize.

**Comment by SJDai-375** [comment]
I also encountered this problem on windwos10 without any exception in debug mode and the same error occurred in release, I used onnxruntime1.11 and cuda11.4

**Comment by SJDai-375** [comment]
> > "nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified"
> 
> When you see this, please go the the build folder and run "make VERBOSE=1", and find the failed nvcc command. Usually, it is because the command has an extra parameter that nvcc wrongly thinks the extra parameter is a file name. That's why it says "A single input file is required ". So, without seeing what the full command line, we can't know what went wrong. And, as @pranavsharma said above, we don't support CUDA 10.2 anymore. So very likely the error was because we were using a new parameter that the old CUDA version didn't recognize.

I also encountered this problem on windwos10 without any exception in debug mode and the same error occurred in release, I used onnxruntime1.11 and cuda11.4

**Comment by SJDai-375** [comment]
> > "nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified"
> 
> When you see this, please go the the build folder and run "make VERBOSE=1", and find the failed nvcc command. Usually, it is because the command has an extra parameter that nvcc wrongly thinks the extra parameter is a file name. That's why it says "A single input file is required ". So, without seeing what the full command line, we can't know what went wrong. And, as @pranavsharma said above, we don't support CUDA 10.2 anymore. So very likely the error was because we were using a new parameter that the old CUDA version didn't recognize.

5>E:\onnxruntime\cmake\out\build\x64-Release>"C:\CUDADe\bin\nvcc.exe" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" -gencode=arch=compute_80,code=\"sm_80,compute_80\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -IE:\onnxruntime\include\onnxruntime -IE:\onnxruntime\include\onnxruntime\core\session -I"E:\onnxruntime\cmake\out\build\x64-Release" -IE:\onnxruntime\onnxruntime -I"E:\onnxruntime\cmake\out\build\x64-Release\_deps\abseil_cpp-src" -IE:\onnxruntime\cmake\external\SafeInt -IE:\onnxruntime\cmake\external\mp11\include -IE:\onnxruntime\cmake\external\pytorch_cpuinfo\include -IE:\onnxruntime\cmake\external\onnx -I"E:\onnxruntime\cmake\out\build\x64-Release\external\onnx" -IE:\onnxruntime\cmake\external\protobuf\src -IE:\onnxruntime\cmake\external\flatbuffers\include -IC:\cuda\include -IE:\onnxruntime\cmake\external\eigen -IC:\CUDADe\include -IE:\onnxruntime\include\onnxruntime -IE:\onnxruntime\include\onnxruntime\core\session -I"E:\onnxruntime\cmake\out\build\x64-Release" -IE:\onnxruntime\onnxruntime -I"E:\onnxruntime\cmake\out\build\x64-Release\_deps\abseil_cpp-src" -IE:\onnxruntime\cmake\external\SafeInt -IE:\onnxruntime\cmake\external\mp11\include -IE:\onnxruntime\cmake\external\pytorch_cpuinfo\include -IE:\onnxruntime\cmake\external\onnx -I"E:\onnxruntime\cmake\out\build\x64-Release\external\onnx" -IE:\onnxruntime\cmake\external\protobuf\src -IE:\onnxruntime\cmake\external\flatbuffers\include -IC:\cuda\include -IE:\onnxruntime\cmake\external\eigen -IC:\CUDADe\include -IC:\CUDADe\include -IC:\CUDADe\include     --keep-dir x64\Release  -maxrregcount=0  --machine 64 --compile -cudart shared --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=expr_has_no_effect /Zi --threads 8 -std=c++17 -Xcompiler="/EHsc -Ob2 /utf-8 /sdl /guard:cf"   -D_WINDOWS -DNDEBUG -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DONNX_USE_LITE_PROTO=1 -D__ONNX_NO_DOC_STRINGS -DTS_USE_NEW_FBS=1 -DTS_SUPPORT_DYNAMIC_INPUT -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -DWIN32 -D_WINDOWS -DCPUINFO_SUPPORTED -DEIGEN_HAS_C99_MATH -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DONNX_USE_LITE_PROTO=1 -D__ONNX_NO_DOC_STRINGS -DTS_USE_NEW_FBS=1 -DTS_SUPPORT_DYNAMIC_INPUT -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdonnxruntime_providers_cuda.dir\Release\vc142.pdb /FS   /MD /GR" -o onnxruntime_providers_cuda.dir\Release\beam_search_implobj "E:\onnxruntime\onnxruntime\contrib_ops\cuda\transformers\beam_search_impl.cu"
5>CUDACOMPILE : nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
5>nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.4.targets(785,9): error MSB3721: 命令“"C:\CUDADe\bin\nvcc.exe" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" -gencode=arch=compute_80,code=\"sm_80,compute_80\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -IE:\onnxruntime\include\onnxruntime -IE:\onnxruntime\include\onnxruntime\core\session -I"E:\onnxruntime\cmake\out\build\x64-Release" -IE:\onnxruntime\onnxruntime -I"E:\onnxruntime\cmake\out\build\x64-Release\_deps\abseil_cpp-src" -IE:\onnxruntime\cmake\external\SafeInt -IE:\onnxruntime\cmake\external\mp11\include -IE:\onnxruntime\cmake\external\pytorch_cpuinfo\include -IE:\onnxruntime\cmake\external\onnx -I"E:\onnxruntime\cmake\out\build\x64-Release\external\onnx" -IE:\onnxruntime\cmake\external\protobuf\src -IE:\onnxruntime\cmake\external\flatbuffers\include -IC:\cuda\include -IE:\onnxruntime\cmake\external\eigen -IC:\CUDADe\include -IE:\onnxruntime\include\onnxruntime -IE:\onnxruntime\include\onnxruntime\core\session -I"E:\onnxruntime\cmake\out\build\x64-Release" -IE:\onnxruntime\onnxruntime -I"E:\onnxruntime\cmake\out\build\x64-Release\_deps\abseil_cpp-src" -IE:\onnxruntime\cmake\external\SafeInt -IE:\onnxruntime\cmake\external\mp11\include -IE:\onnxruntime\cmake\external\pytorch_cpuinfo\include -IE:\onnxruntime\cmake\external\onnx -I"E:\onnxruntime\cmake\out\build\x64-Release\external\onnx" -IE:\onnxruntime\cmake\external\protobuf\src -IE:\onnxruntime\cmake\external\flatbuffers\include -IC:\cuda\include -IE:\onnxruntime\cmake\external\eigen -IC:\CUDADe\include -IC:\CUDADe\include -IC:\CUDADe\include     --keep-dir x64\Release  -maxrregcount=0  --machine 64 --compile -cudart shared --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=expr_has_no_effect /Zi --threads 8 -std=c++17 -Xcompiler="/EHsc -Ob2 /utf-8 /sdl /guard:cf"   -D_WINDOWS -DNDEBUG -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DONNX_USE_LITE_PROTO=1 -D__ONNX_NO_DOC_STRINGS -DTS_USE_NEW_FBS=1 -DTS_SUPPORT_DYNAMIC_INPUT -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -DWIN32 -D_WINDOWS -DCPUINFO_SUPPORTED -DEIGEN_HAS_C99_MATH -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DONNX_USE_LITE_PROTO=1 -D__ONNX_NO_DOC_STRINGS -DTS_USE_NEW_FBS=1 -DTS_SUPPORT_DYNAMIC_INPUT -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdonnxruntime_providers_cuda.dir\Release\vc142.pdb /FS   /MD /GR" -o onnxruntime_providers_cuda.dir\Release\beam_search_implobj "E:\onnxruntime\onnxruntime\contrib_ops\cuda\transformers\beam_search_impl.cu"”已退出，返回代码为 1。

**Comment by natke** [comment]
Docs issue fixed by #14789
