### ISSUE TITLE
Errors when I try to load two model in two GPUs

### ISSUE THREAD

**Issue by busishengui** [microsoft/onnxruntime#15091]
### Describe the issue

I try to load different models into different GPUs，But I fail

2023-03-17 09:51:15.106049476 [E:onnxruntime:, inference_session.cc:1341 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:115 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 7: CUDNN_STATUS_MAPPING_ERROR ; GPU=1 ; hostname=lv-voice-rt-02 ; expr=cudnnSetStream(cudnn_handle_, stream); 

terminate called after throwing an instance of 'Ort::Exception'
  what():  Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:115 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 7: CUDNN_STATUS_MAPPING_ERROR ; GPU=1 ; hostname=lv-voice-rt-02 ; expr=cudnnSetStream(cudnn_handle_, stream); 

### To reproduce

    Ort::Env env;
    Ort::SessionOptions session_options;
    OrtCUDAProviderOptions options;
    options.device_id = 0; 
    options.arena_extend_strategy = 1;
    options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::DEFAULT;
    options.default_memory_arena_cfg = nullptr;
    options.do_copy_in_default_stream = 1;
    session_options.SetInterOpNumThreads(1);
    session_options.SetIntraOpNumThreads(1);
    session_options.AppendExecutionProvider_CUDA(options);
    Ort::Session session(env, "model.onnx", session_options);
        Ort::Env env1;
    Ort::SessionOptions session_options1;
    OrtCUDAProviderOptions options1;
    options1.device_id = 1; 
    options1.arena_extend_strategy = 1;
    options1.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::DEFAULT;
    options1.default_memory_arena_cfg = nullptr;
    options1.do_copy_in_default_stream = 1;
    session_options1.SetInterOpNumThreads(1);
    session_options1.SetIntraOpNumThreads(1);
    session_options1.AppendExecutionProvider_CUDA(options1);
    Ort::Session session1(env1, "model2.onnx", session_options1);

### Platform

Linux

### OS Version

Centos

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.8.1-gpu

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA11.0

**Comment by skottmckay** [comment]
Can you strip things down to the bare miminum, as well as only using one Env instance and see if that works?

Something like: 

```
Ort::Env env;

Ort::SessionOptions session_options;
OrtCUDAProviderOptions options;
options.device_id = 0; 
session_options.AppendExecutionProvider_CUDA(options);
Ort::Session session(env, "model.onnx", session_options);

Ort::SessionOptions session_options1;
OrtCUDAProviderOptions options1;
options1.device_id = 1; 
session_options1.AppendExecutionProvider_CUDA(options1);
Ort::Session session1(env, "model2.onnx", session_options1);
```

**Comment by busishengui** [comment]
> 您能否将事情精简到最低限度，以及仅使用一个 Env 实例，看看是否可行？
> 
> 就像是：
> 
> ```
> Ort::Env env;
> 
> Ort::SessionOptions session_options;
> OrtCUDAProviderOptions options;
> options.device_id = 0; 
> session_options.AppendExecutionProvider_CUDA(options);
> Ort::Session session(env, "model.onnx", session_options);
> 
> Ort::SessionOptions session_options1;
> OrtCUDAProviderOptions options1;
> options1.device_id = 1; 
> session_options1.AppendExecutionProvider_CUDA(options1);
> Ort::Session session1(env, "model2.onnx", session_options1);
> ```

Thanks, it works
