### ISSUE TITLE
Cannot create inference session with CUDAExecutionProvider

### ISSUE THREAD

**Issue by chinmayjog13** [microsoft/onnxruntime#15718]
### Describe the issue

Onnxruntime fails to create an inference session with CUDAExecutionProvider. It works fine on CPU. I suspect nvidia driver updates might have caused this as this didn't happen before yesterday. The model file does not matter as it fails with all models I have tried with. All my model files are well under 2GB.

This is the error message I get
`
2023-04-27 14:33:08.771864172 [E:onnxruntime:, inference_session.cc:1529 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=5 ; hostname=mcfluid03 ; expr=cudnnCreate(&cudnn_handle_); 

Traceback (most recent call last):
  File "create_match_fd_input.py", line 48, in <module>
    model = ONNX_model('dummy_tfv6.onnx', use_gpu=True)
  File "/home/chinmay/fd_match_experiment/onnx_model.py", line 23, in __init__
    self.ort_session = ort.InferenceSession(model_file, providers=[('CUDAExecutionProvider', {'device_id': gpu_id,})])
  File "/home/chinmay/anaconda3/envs/v_pytorch/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/chinmay/anaconda3/envs/v_pytorch/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=5 ; hostname=mcfluid03 ; expr=cudnnCreate(&cudnn_handle_);

`

### To reproduce

It is a basic code, where I import onnxruntime and try to create an inference session.
`
import onnxruntime as ort

gpu_id = 5
model_file = 'dummy_tfv6.onnx'
ort_session = ort.InferenceSession(model_file, providers=[('CUDAExecutionProvider', {'device_id': gpu_id,})])

`

### Urgency

Somewhat urgent. I need to fix this to develop a commercial product, it was working fine till yesterday.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1, 1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

11.6

**Comment by tianleiwu** [comment]
Try install cudnn: `pip install nvidia-cudnn-cu11==8.5.0.96`

**Comment by chinmayjog13** [comment]
I still get the same error.

**Comment by chinmayjog13** [comment]
Reinstalling correct cuDNN version solved the issue.

**Comment by divyansh2681** [comment]
Hi,
I have CUDA 11.8, cuDNN 8.7.0 and onnxruntime 1.15, still I am facing the same issue. Any help would be appreciated!

**Comment by tianleiwu** [comment]
@divyansh2681, the reason can be many (including GPU driver, multiple versions of CUDA or cuDNN installed). 

You can add a few lines of python code to dump DLLs before creating session:
```
    import psutil
    p = psutil.Process(os.getpid())
    for lib in p.memory_maps():
          print(lib.path)
```

**Comment by divyansh2681** [comment]
> @divyansh2681, the reason can be many (including GPU driver, multiple versions of CUDA or cuDNN installed).
> 
> You can add a few lines of python code to dump DLLs before creating session:
> 
> ```
>     import psutil
>     p = psutil.Process(os.getpid())
>     for lib in p.memory_maps():
>           print(lib.path)
> ```

Thank you for your response! I was able to resolve the issue. It was a pytorch error. Pytorch occupied the cache memory of the GPU. I used ```cudaDeviceReset()``` in my inference code. It is a part of ```cuda_runtime_api.h```.
Reference: https://stackoverflow.com/questions/66588715/runtimeerror-cudnn-error-cudnn-status-not-initialized-using-pytorch
