### ISSUE TITLE
ROCm execution provider fails on 7900 XTX with strange error.

### ISSUE THREAD

**Issue by borg323** [microsoft/onnxruntime#16566]
### Describe the issue

Trying to run lc0 built with onnxruntime-rocm and ROCm 5.6 on a 7900 XTX fails with: `2023-07-02 18:00:40.696679830 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Relu node. Name:'/inputconv/relu' Status Message: HIP error hipErrorInvalidDeviceFunction:invalid device function`

### To reproduce

Build lc0 with onnxruntime-rocm support from <https://github.com/LeelaChessZero/lc0/pull/1897> and use any LeelaChessZero weights file.

### Urgency

Not urgent.

### Platform

Linux

### OS Version

ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

f46956056d7f8ea214e794e5cbedee36f21f7ea2

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

ROCm 5.6

**Comment by cloudhan** [comment]
@borg323 Could you provide the command line you used for building from source? `hipErrorInvalidDeviceFunction` indicate an architecture mismatch.

For onnxruntime itself, the hip arch is populated from cmake as follows. By default, it does not contain a gfx1100 corresponds to  7900 XTX.

https://github.com/microsoft/onnxruntime/blob/f46956056d7f8ea214e794e5cbedee36f21f7ea2/cmake/CMakeLists.txt#L274-L276

There is another case that we deeply integrate with composable kernel where it hardcoded hip archs in its CMakeLists.txt 

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/7797bd3d2b047ab6ccd7b3618bf40f79bf234723/library/src/tensor_operation_instance/gpu/CMakeLists.txt#L51-L56 You might need to disable ck as a whole for now.

Could you please try out the follow commands
```bash
build.sh \
        --build_dir build \
        --config Release \
        --cmake_generator Ninja \
        --cmake_extra_defines \
            CMAKE_HIP_ARCHITECTURES=gfx906,gfx1030,gfx1100 \
            onnxruntime_USE_COMPOSABLE_KERNEL=OFF \
        --use_rocm \
        --build_wheel --rocm_version 5.4.3 \
        --rocm_home=/opt/rocm-5.4.3 --nccl_home=/opt/rocm \
        --skip_submodule_sync --skip_tests
```

A further note is that we primarily built onnxruntime for our internal CDNA2 arch cards and only run tests for gfx90a and gfx908.  We cannot support customer grade cards due to the lacking of CI machines.

**Comment by borg323** [comment]
Thanks, this fixed the issue.

**Comment by Displacer** [comment]
exact build command was:

./build.sh --allow_running_as_root --cmake_extra_defines ONNXRUNTIME_VERSION=`cat ./VERSION_NUMBER` \
    	    CMAKE_HIP_ARCHITECTURES=gfx906,gfx1030,gfx1100 \
            onnxruntime_USE_COMPOSABLE_KERNEL=OFF \
	    --config Release --parallel \
            --skip_tests --build_wheel --build_shared_lib --use_rocm --rocm_version=${ROCM_VERSION} --rocm_home /opt/rocm --use_migraphx 

with rocm-5.6
