### ISSUE TITLE
CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED - when using onnxruntime with CUDA execution provider

### ISSUE THREAD

**Issue by divyansh2681** [microsoft/onnxruntime#17337]
### Describe the issue

I am using onnxruntime C++ API to deploy a model. When I use the CUDAExecutionProvider, I get the error below:

terminate called after throwing an instance of 'Ort::Exception'
  what():  /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname=divyansh-moon ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_stream_handle.cc ; line=52 ; expr=cudnnCreate(&cudnn_handle_); 

I get a similar error when using the python API as well. 

### To reproduce

```
#include <torch/torch.h>
#include <torch/script.h>
#include <ATen/ATen.h>
#include <iostream>
#include <string>
#include <random>
#include <sndfile.h>
#include <vector>
#include <memory>
#include <cmath>
#include <yaml-cpp/yaml.h>
#include <numeric>
#include <AudioFile.h>
#include "onnxruntime_cxx_api.h"

void runInference () {
    std::string configPath = "/home/stt_en_fastconformer_ctc_xxlarge.yaml";
    std::string modelPath = "/home/stt_en_fastconformer_ctc_xxlarge.onnx";
    std::string preprocessorPath = "/home/tmp.pt";

    std::string instanceName = "asr";
    Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, instanceName.c_str());
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);
    std::cout << "CP 1" << std::endl;
    sessionOptions.AppendExecutionProvider_CUDA(OrtCUDAProviderOptions{});
    std::cout << "CP 2" << std::endl;
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
    // sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    Ort::Session session(env, modelPath.c_str(), sessionOptions);
    Ort::AllocatorWithDefaultOptions allocator;

    size_t numInputNodes = session.GetInputCount();
    size_t numOutputNodes = session.GetOutputCount();

    auto input0Name = session.GetInputNameAllocated(0, allocator);
    Ort::TypeInfo input0TypeInfo = session.GetInputTypeInfo(0);
    auto input0TensorInfo = input0TypeInfo.GetTensorTypeAndShapeInfo();
    ONNXTensorElementDataType input0Type = input0TensorInfo.GetElementType();
    std::vector<int64_t> input0Dims = {1, 80, 400};

    auto input1Name = session.GetInputNameAllocated(1, allocator);
    Ort::TypeInfo input1TypeInfo = session.GetInputTypeInfo(1);
    auto input1TensorInfo = input1TypeInfo.GetTensorTypeAndShapeInfo();
    ONNXTensorElementDataType input1Type = input1TensorInfo.GetElementType();
    std::vector<int64_t> input1Dims = {1};

    auto outputName = session.GetOutputNameAllocated(0, allocator);
    Ort::TypeInfo outputTypeInfo = session.GetOutputTypeInfo(0);
    auto outputTensorInfo = outputTypeInfo.GetTensorTypeAndShapeInfo();
    ONNXTensorElementDataType outputType = outputTensorInfo.GetElementType();
    std::vector<int64_t> outputDims = {1, 50, 1025};

    const char* filePath = "/home/AAN3_16khz.wav";
    
    torch::Tensor signalData = generateTensorFromWave(filePath);
    int64_t signalSize = signalData.size(1);
    torch::Tensor signalLength = torch::tensor({signalSize}, torch::kLong).unsqueeze(0);
    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(signalData);
    inputs.push_back(signalLength);

    torch::jit::script::Module preprocessor = generatePreprocessor(preprocessorPath);
    torch::jit::IValue outputPreprocessor = preprocessor.forward(inputs);

    torch::Tensor outputTensor1 = outputPreprocessor.toTuple()->elements()[0].toTensor();
    torch::Tensor outputTensor2 = outputPreprocessor.toTuple()->elements()[1].toTensor();

    size_t outputTensorSize = vectorProduct(outputDims);
    std::vector<float> outputTensorValues(outputTensorSize);

    std::vector<Ort::Value> inputTensors;
    std::vector<Ort::Value> outputTensors;
    std::cout << "CP 3" << std::endl;
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(
        OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
    std::cout << "CP 4" << std::endl;


    inputTensors.push_back(Ort::Value::CreateTensor<float>(
        memoryInfo, outputTensor1.data_ptr<float>(), outputTensor1.numel(), input0Dims.data(), input0Dims.size()));
    inputTensors.push_back(Ort::Value::CreateTensor<int64_t>(
        memoryInfo, outputTensor2.data_ptr<int64_t>(), outputTensor2.numel(), input1Dims.data(), input1Dims.size()));
    std::cout << "CP 5" << std::endl;
    outputTensors.push_back(Ort::Value::CreateTensor<float>(
        memoryInfo, outputTensorValues.data(), outputTensorValues.size(),
        outputDims.data(), outputDims.size()));

    std::cout << "CP 6" << std::endl;
    std::vector<const char*> input_names = {input0Name.get(), input1Name.get()};
    std::vector<const char*> output_names = {outputName.get()};
    std::cout << "CP 7" << std::endl;
    session.Run(Ort::RunOptions{nullptr}, input_names.data(),
            inputTensors.data(), 2 /*Number of inputs*/, output_names.data(),
            outputTensors.data(), 1 /*Number of outputs*/);

    std::cout << "CP 8" << std::endl;
    std::vector<std::vector<std::vector<float>>> reshapedVector(1,
    std::vector<std::vector<float>>(50, std::vector<float>(1025)));

    size_t idx = 0;
    for (size_t i = 0; i < 1; ++i) {
        for (size_t j = 0; j < 50; ++j) {
            for (size_t k = 0; k < 1025; ++k) {
                reshapedVector[i][j][k] = outputTensorValues[idx];
                idx = idx + 1;
            }
        }
    }
}



int main(int argc, const char* argv[]) {
    
    runInference();
    return 0;
}
```

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

**Comment by mszhanyi** [comment]
CUDNN_STATUS_NOT_INITIALIZED is often caused by incorrect GPU driver (insufficient driver version) or wrong version of cuDNN.
Could you share more info with the below commands
`nvcc --version`  (cuda version)
`cat /proc/driver/nvidia/version` (cuda driver version)
`cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2` (cudnn version)

**Comment by divyansh2681** [comment]
> cat /proc/driver/nvidia/version

Thank you for your response!

```
NVRM version: NVIDIA UNIX x86_64 Kernel Module  535.86.10  Wed Jul 26 23:20:03 UTC 2023
GCC version:  gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```
I don't have a directory /usr/local/cuda
I have a directory /usr/local/cuda-11.8 but it does not have cudnn.h

The only location where I have cudnn.h is /usr/include and it does not have any information about cudnn version

I have a cudnn_version.h in /usr/include and the output of 
```
cat /usr/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
``` 
is:
```
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 7
#define CUDNN_PATCHLEVEL 0
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

/* cannot use constexpr here since this is a C-only file */
```

**Comment by mszhanyi** [comment]
Maybe the cuDNN isn't installed correctly.
Could you check out https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-821/install-guide/index.html#verify .

**Comment by divyansh2681** [comment]
Yes, I verified the installation, it passed. I had to install Freeimage before that. It is required to run the verification executable.

**Comment by divyansh2681** [comment]
@mszhanyi are there any other ways to debug this issue?

**Comment by divyansh2681** [comment]
@mszhanyi are there any other ways to debug this issue? 
When  I do ```cmake ..```  I get ```-- USE_CUDNN is set to 0. Compiling without cuDNN support```

**Comment by divyansh2681** [comment]
Hello @snnn, can you please help me with this issue?

**Comment by mszhanyi** [comment]
> When I do `cmake ..` I get `-- USE_CUDNN is set to 0. Compiling without cuDNN support`

did you set `--cudnn_home`? since the cudnn you installed isn't under cuda directory.

**Comment by snnn** [comment]
Can you try cudnn 8.9? That one is newer

**Comment by divyansh2681** [comment]
> Can you try cudnn 8.9? That one is newer

I tried 8.9 as well, getting the same error. Do I need to include anything related to cudnn in my cmakelists.txt? And where do I set the ```--cudnn_home```? I have given my cmakelists.txt below. 

```
cmake_minimum_required(VERSION 3.18 FATAL_ERROR)
project(transcribe)

include_directories(
    ${CMAKE_SOURCE_DIR}
    /home/divyansh/Documents/onnxruntime-linux-x64-gpu-1.15.1/include
    ${CMAKE_SOURCE_DIR}/audio)

link_directories(/home/divyansh/Documents/onnxruntime-linux-x64-gpu-1.15.1/lib 
/home/divyansh/.local/lib/python3.10/site-packages/torchaudio/lib) 

link_libraries(/home/divyansh/voiceRecog-test/audio/build/torchaudio/csrc/sox/libtorchaudio_sox.so)
set(Torch_DIR /home/divyansh/.local/lib/python3.10/site-packages/torch/share/cmake/Torch)
find_package(Torch REQUIRED)
add_executable(transcribe transcribe.cpp)
target_link_libraries(transcribe PRIVATE "${TORCH_LIBRARIES}" onnxruntime torchaudio)
set_property(TARGET transcribe PROPERTY CXX_STANDARD 17)
```

**Comment by divyansh2681** [comment]
I was able to resolve the issue. It was a pytorch error. Pytorch occupied the cache memory of the GPU at the beginning of the program. I used ```cudaDeviceReset();``` in my inference code. It is a part of ```cuda_runtime_api.h```. 
Reference: https://stackoverflow.com/questions/66588715/runtimeerror-cudnn-error-cudnn-status-not-initialized-using-pytorch

**Comment by divyansh2681** [comment]
@snnn I have another question - When I use OrtCUDAProviderOptions (GPU) with my session, the runtime is 2x as compared to using only the CPU. This looks weird to me. Can this be due to data transfer between CPU and GPU? I am not doing any data transfer manually through my code though.

**Comment by snnn** [comment]
I'm sorry that is beyond of my knowledge. I only know some parts of the code.
