### ISSUE TITLE
 CUDAExecutionProvider providers

### ISSUE THREAD

**Issue by ahmasoum** [microsoft/onnxruntime#17864]
### Describe the issue

hello, I try different ways to use CUDAExecutionProvider providers.
now i try cuda dockerfile. after solving a lot of problems, the image was built.
after that i created a container from this image by this command:
`sudo docker run --name onnxr_cuda -itd -v ... --gpus all 04c2f449baa3 bash`
inside of container, when i try `ort.get_available_providers()` code, it returns `['CUDAExecutionProvider', 'CPUExecutionProvider'] `.
but when i try `sess = InferenceSession(model_path, providers=['CUDAExecutionProvider'],sess_options=options)` it return 
```
EP Error /code/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /code/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 804: forward compatibility was attempted on non supported HW ; GPU=0 ; hostname=365547a6e681 ; file=/code/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id); 

 when using ['CUDAExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
```
please help me.

### To reproduce

...

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1

**Comment by pranavsharma** [comment]
1.16 release is not built for CUDA 12.x. It's using 11.8. The error message does hint about this: CUDA failure 804: forward compatibility was attempted on non supported HW.

**Comment by ahmasoum** [comment]
@p

> 1.16 release is not built for CUDA 12.x. It's using 11.8. The error message does hint about this: CUDA failure 804: forward compatibility was attempted on non supported HW.

but in dockerfile of tag 1.16.0, cuda 12.1 has been consumed. https://github.com/microsoft/onnxruntime/blob/e7a0495a874251e9747b2ce0683e0580282c54df/dockerfiles/Dockerfile.cuda#L8C1-L8C57

**Comment by pranavsharma** [comment]
Not sure how and if the dockerfile works. 1.16 is _definitely_ not built with cuda 12.

**Comment by snnn** [comment]
The docker file you pointed to builds onnxruntime from source, so it can use a different CUDA version.

**Comment by tianleiwu** [comment]
Check is whether `CMAKE_CUDA_ARCHITECTURES=52;60;61;70;75;86'` is compatible with your GPU. If you runs on H100, you might need add 90.

**Comment by ahmasoum** [comment]
> @ahmasoum, Check whether [CMAKE_CUDA_ARCHITECTURES=52;60;61;70;75;86'](https://github.com/microsoft/onnxruntime/blob/e7a0495a874251e9747b2ce0683e0580282c54df/dockerfiles/Dockerfile.cuda#L17) is compatible with your GPU. If you run on H100, you might need add 90.
> 
> I also saw a similar issue [here](https://discuss.pytorch.org/t/docker-error-804-forward-compatibility/122644). The suggestions is to update GPU driver (it might not match with CUDA 12.1).

my GPU is 3060. is it possible not compatible?

**Comment by tianleiwu** [comment]
@ahmasoum, 3060 is good, it is 86. Then it is likely GPU driver issue according the [similar issue](https://discuss.pytorch.org/t/docker-error-804-forward-compatibility/122644). You might try re-install GPU driver that could support 12.1.

**Comment by ahmasoum** [comment]
thank you. it worked.
