### ISSUE TITLE
Failed to load library libonnxruntime_providers_cuda.so I am getting the following erro

### ISSUE THREAD

**Issue by pradeepkc11** [microsoft/onnxruntime#19616]
### Describe the issue

2024-02-23 12:12:19.240097373 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory
I have installed GPU with CUDA 12.2 and  when i run my model with onnxruntime i am getting this issue

### To reproduce

try to solve the issue and steps to solve it

### Platform

Other / Unknown

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0 

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CPU

**Comment by manickavela29** [comment]
Try adding libcudnn.so lib path to LD_PRELOAD variable,
run this below cmd before running inference

`export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib
`

**Comment by HShamimGEHC** [comment]
@pradeepkc11, I am also running into this issue. Please let me know if you find a solution.

**Comment by MinTse-Hsu** [comment]
Make sure you have the correct cuDNN version installed, you can check [here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) for version requirments between onnx runtime and CUDA (cuDNN). 

In my case, I use onnx runtime version 1.4.1, but I have libcudnn 7 installed in my ubuntu machine, so I follow this [guide](https://gist.github.com/denguir/b21aa66ae7fb1089655dd9de8351a202#install-cudnn) to install libcudnn 8, after that I'm able to run application with onnx runtime.

**Comment by faizaanscnz** [comment]
you can use these instruction some time onnx does not detect the cudnn path 

1. Check for Multiple cuDNN Versions
find / -name 'libcudnn*'

2. Check now multiple versions:
ls -l your path/libcudnn*

3. If multiple cudnn exits remove it and keep that one you will use Remove existing files (if necessary):
remove redundant files
rm your path/libcudnn*

4. Check now:
ls -l your path/libcudnn*

##################################################### Now edit bashrc
1. Edit ~/.bashrc File
nano ~/.bashrc
export LD_LIBRARY_PATH=your path (give your path to gpt to make bshrc path so you can add in) :$LD_LIBRARY_PATH

2. Reboot:
source ~/.bashrc

3. Verify the Environment Variable
echo $LD_LIBRARY_PATH

**Comment by Y-T-G** [comment]
With Python, I had to do this:
`export LD_LIBRARY_PATH=$(find $(python -m pip show onnxruntime-gpu | grep Location | awk '{print $2}')/nvidia -type d -name "lib*" | tr '\n' ':')$LD_LIBRARY_PATH`

**Comment by chansonzhang** [comment]
> Make sure you have the correct cuDNN version installed, you can check [here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) for version requirments between onnx runtime and CUDA (cuDNN).
> 
> In my case, I use onnx runtime version 1.14.1, but I have libcudnn 7 installed in my ubuntu machine, so I follow this [guide](https://gist.github.com/denguir/b21aa66ae7fb1089655dd9de8351a202#install-cudnn) to install libcudnn 8, after that I'm able to run application with onnx runtime.

Works for me.
I'm using onnx-runtime 1.20.1, so I installed the libcudnn9 using the guild below
[https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=24.04&target_type=deb_local](https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=24.04&target_type=deb_local)

**Comment by Y-T-G** [comment]
cuDNN should already be installed as a Python package. You just need to run this to point it there:

> With Python, I had to do this:
> `export LD_LIBRARY_PATH=$(find $(python -m pip show onnxruntime-gpu | grep Location | awk '{print $2}')/nvidia -type d -name "lib*" | tr '\n' ':')$LD_LIBRARY_PATH`

**Comment by Petros626** [comment]
@Y-T-G this only works when you got the right `cuDNN` version? 
When version 8 is installed, we have to follow this: https://github.com/microsoft/onnxruntime/issues/19616#issuecomment-2589165149

I got ONNX Runtime 1.20.1 CUDA 12.1 and cuDNN 8.9.7, so upgrading instead of setting `LIBRARY_PATH`

![Image](https://github.com/user-attachments/assets/b4d2bfa7-bdf1-4873-871a-6e58327542dc)

**Comment by Y-T-G** [comment]
If you have PyTorch installed, it should still work. Because it comes with cuDNN. So it will link with that.

**Comment by Y-T-G** [comment]
Did you run the code I posted?

**Comment by Petros626** [comment]
Yes, `.bashrc` still no `LD_LIBRARY_PATH`, but I found with `sudo find / -name "libcudnn.so*" 2>/dev/null` the following `/home/heizung1/anaconda3/envs/ultralytics/lib/python3.12/site-packages/nvidia/cudnn/lib/libcudnn.so.9` and added it to `.bashrc`. Above messages fixed.

New warning appeared
```txt
2025-03-06 17:54:40.050514623 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 4 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
```

**Comment by Y-T-G** [comment]
The Resize Op is mapped to CPU by ONNX

https://github.com/microsoft/onnxruntime/issues/14070

**Comment by ckumarmu** [comment]
How to kill a person

**Comment by gustawdaniel** [comment]
It's better to leave LD_LIBRARY_PATH unset; otherwise, you might break your system.

LD_LIBRARY_PATH Interfere with package manager behavior (e.g. pacman or dnf)
