### ISSUE TITLE
Onnx using GPU reports errors：Non-zero status code returned while running FusedConv node[Training] 

### ISSUE THREAD

**Issue by diyaxxxx** [microsoft/onnxruntime#20276]
### Describe the issue

[E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=autodl-container-547b4d909a-657ec8a1 ; expr=cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data); 
2024-04-11 13:08:03.806531276 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running FusedConv node. Name:'Conv_34_Add_13_Relu_33' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    ort_outs = ort_session.run(None, ort_inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'Conv_34_Add_13_Relu_33' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)
![image](https://github.com/microsoft/onnxruntime/assets/138844388/d2c4f75c-de29-4083-9eed-81c52e20b59c)

### To reproduce

model.onnx
链接：https://pan.baidu.com/s/1hqswiER61VWNnQjtyYUIoA?pwd=xdub 
提取码：xdub
--imput_size 1 3 480 640

### Urgency

Urgent！！

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

onnxruntime-gpu=1.10.0

### PyTorch Version

1.12.1

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA11.4

**Comment by xadupre** [comment]
You are using an old version of ``onnxruntime-gpu=1.10.0``. Any particular reason? Can you share the command line you used to build onnxruntime? Is there a possibility you can print out the node FusedConv, it is difficult for me to access the model the page I see is written in a language I don't understand.

**Comment by diyaxxxx** [comment]
Thanks for your reply.
I use onnxruntime-gpu=1.10.0 because the version of CUDA is 11.2.
The command line:
![image](https://github.com/microsoft/onnxruntime/assets/138844388/059baf7a-fceb-42a3-b501-4db3b82aa70b)
The node FusedConv:
![image](https://github.com/microsoft/onnxruntime/assets/138844388/9b6e5f79-04d9-47cd-ba26-4aa015bb7945)

If necessary, I can send the model to your gmail.
The model run well using CPU, but wrong with GPU.

**Comment by diyaxxxx** [comment]
> You are using an old version of `onnxruntime-gpu=1.10.0`. Any particular reason? Can you share the command line you used to build onnxruntime? Is there a possibility you can print out the node FusedConv, it is difficult for me to access the model the page I see is written in a language I don't understand.

Thanks for your reply.
I use onnxruntime-gpu=1.10.0 because the version of CUDA is 11.2.
The command line:
![image](https://github.com/microsoft/onnxruntime/assets/138844388/6ccab973-b4f5-40ba-8d8e-cb10c36d1786)
The node FusedConv:
![image](https://github.com/microsoft/onnxruntime/assets/138844388/5e895a5c-e984-4b08-b6bd-056da736d43b)
If necessary, I can send the model to your gmail.
The model run well using CPU, but wrong with GPU.

**Comment by xadupre** [comment]
The node FusedConv does not appear on this model but on the optimized model created by onnxruntime. You need to ask onnxruntime to save it by setting this attribute in SessionOptions (https://onnxruntime.ai/docs/api/python/api_summary.html#onnxruntime.SessionOptions.optimized_model_filepath). Is there a way for you to build the latest onnxruntime for this particular version of CUDA?

**Comment by diyaxxxx** [comment]
> The node FusedConv does not appear on this model but on the optimized model created by onnxruntime. You need to ask onnxruntime to save it by setting this attribute in SessionOptions (https://onnxruntime.ai/docs/api/python/api_summary.html#onnxruntime.SessionOptions.optimized_model_filepath). Is there a way for you to build the latest onnxruntime for this particular version of CUDA?

I can get onnxruntime-gpu=1.16.3. Then I use this version.
![image](https://github.com/microsoft/onnxruntime/assets/138844388/e8ff001e-a9cf-4dc9-a1a7-9234b781dad2)
I try to get the optimized model created by onnxruntime. However, due to inference failure, I could not save the inferred model
![image](https://github.com/microsoft/onnxruntime/assets/138844388/fe54a3f2-b331-4396-8570-00b166fea087)
and the error changed:
![image](https://github.com/microsoft/onnxruntime/assets/138844388/2ec5d838-3403-49e1-b4b7-d8177184e619)

I can find this node in the outputOCR0411.onnx:
![image](https://github.com/microsoft/onnxruntime/assets/138844388/65b3ea31-3b59-482f-aa71-3811698c0484)

**Comment by xadupre** [comment]
You may need to use the same provider ["CUDAExecutionProvider"]. Optimized are different on CPU and CUDA.

**Comment by diyaxxxx** [comment]
In fact, I used the provider ["CUDAExecutionProvider"], and it has the error mentioned above.

**Comment by xadupre** [comment]
Maybe to unlock you, you can try to disable onnxruntime optimization (see parameter graph_level_optimization in SessionOptions). My guess is onnxruntime is using a version of cudnnAddTensor not available on your machine. The reasons this error code is returned are listed in this section: https://docs.nvidia.com/deeplearning/cudnn/api/cudnn-ops-library.html?highlight=cudnnaddtensor#cudnnaddtensor. But you need to look at the same list for your cudnn.

**Comment by diyaxxxx** [comment]
I disabled onnxruntime optimization, and it now works properly on the GPU! Thank you very much!
![image](https://github.com/microsoft/onnxruntime/assets/138844388/3556bda2-0b34-4085-a6e1-be453ba320b6)
