### ISSUE TITLE
[TensorRT ExecutionProvider] Cannot infer the model on a GPU device with an ID other than 0

### ISSUE THREAD

**Issue by dat58** [microsoft/onnxruntime#21276]
### Describe the issue

In a scenario where multiple GPU devices are available, when selecting the TensorrtExecutionProvider and choosing device_id = 0, the model infers perfectly. However, when using a different device_id (not equal to 0), an error is thrown during inference:
```
[2024-07-06 07:03:24   ERROR] 1: [reformat.cpp::executeCutensor::332] Error Code 1: CuTensor (Internal cuTensor permutate execute failed)
[2024-07-06 07:03:24   ERROR] 1: [checkMacros.cpp::catchCudaError::181] Error Code 1: Cuda Runtime (invalid resource handle)
```

I noticed that a similar problem occurred with the CudaExecutionProvider a few years ago, and it was resolved in issue #1815 (I have tested it, and it works correctly). It is possible that a similar issue has occurred with the TensorrtExecutionProvider.

### To reproduce

Tested on both versions: 
  - tensorrt@8.6.1.6-1+cuda11.8
  - tensorrt@10.0.1.6-1+cuda11.8

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3 | 1.17.3 | 1.18.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.8

**Comment by chilo-ms** [comment]
I tried running ResNet50 on device other than 0 with TRT EP, and it can successfully run the inference.

Could you share the script/code to help repro the issue?

**Comment by dat58** [comment]
I have used the [ort@2.0.0-rc.2](https://github.com/pykeio/ort) Rust binding code from C (since I am not familiar with C code). Below is a simple code snippet that I have used::
```Rust
let model_path = "warehouse/model.onnx";
let global_options = ort::EnvironmentGlobalThreadPoolOptions {
            intra_op_parallelism: Some(16),
            ..Default::default()
};
let _ = ort::init().with_global_thread_pool(global_options).commit()?;
let provider = ort::TensorRTExecutionProvider::default()
                        .with_device_id(1)
                        .with_engine_cache(true)
                        .with_engine_cache_path("warehouse".to_owned())
                        .with_profile_min_shapes("images:1x3x256x256".to_owned())
                        .with_profile_opt_shapes("images:32x3x256x256".to_owned())
                        .with_profile_max_shapes("images:64x3x256x256".to_owned())
                        .with_max_partition_iterations(10)                
                        .with_max_workspace_size(2 * 1024 * 1024 * 1024)
                        .build();
let session = Session::builder()?
                .with_optimization_level(ort::GraphOptimizationLevel::Level3)?
                .with_execution_providers([provider])?
                .commit_from_file(model_path)?;
```

Inference with
```Rust
let outputs = session.run_async(inputs)?.await?;
```
I encountered the error mentioned above. However, when I tried running it with the CUDA Execution Provider (EP), it worked perfectly fine.

**Comment by yf711** [comment]
Hi @dat58 does other model work on your script with TensorRT EP and gpu_id=1? Like [ResNet50](https://github.com/onnx/models/blob/main/validated/vision/classification/resnet/model/resnet50-v1-12.tar.gz)?

Btw I saw you previously posted an issue https://github.com/pykeio/ort/issues/226 with gpu_id=0 and same error type. Is this issue still happening to single GPU? If you already fixed it, what did you do to fix?

**Comment by dat58** [comment]
Hi @yf711, posting the issue at [ort](https://github.com/pykeio/ort/issues/226) was my mistake of copying the code incorrectly. It should be gpu_id != 0. I have conducted multiple tests and realized that if I append the Cuda EP after TensorRT (provider = [TensorRTExecutionProvider, CudaExecutionProvider]), the model inference is successful.

**Comment by yf711** [comment]
> Hi @yf711, posting the issue at [ort](https://github.com/pykeio/ort/issues/226) was my mistake of copying the code incorrectly. It should be gpu_id != 0. I have conducted multiple tests and realized that if I append the Cuda EP after TensorRT (provider = [TensorRTExecutionProvider, CudaExecutionProvider]), the model inference is successful.

Thanks for sharing. Did you enable both TRT/CUDA EP to your multiGPU script as well? If so, you are welcome to share your script file and model (without your IP) bundle to help repro this issue.

Btw, are all your multiple GPUs same architecture? Is that possible that your existing engine cache generated by your gpu_id:0 and consumed by gpu_id:1, which has different architecture and not compatible?

**Comment by dat58** [comment]
To reproduce the issue, it could be complicated. I have written a mini Rust code to reproduce this problem. Please download it from the [source](https://drive.google.com/drive/folders/1cEuOeOy--pdKzgr7WAsJ8TxltDHcXAlb?usp=sharing). In my shared folder, there are three files: `Dockerfile`, `run.sh`, `projects.zip`.

The `projects.zip` file contains two projects. The `trtsample` project is used to start the HTTP server, receive incoming requests, and simulate model inference. The `loadtest` project is used to send a large number of requests to the HTTP server.

To create the environment and run the Rust project, use the `Dockerfile` provided.
```bash
docker build -t rustai:ort .
```
And execute `run.sh` to start a container.
```bash
bash run.sh
```
Extract file `projects.zip` to your $HOME folder
![image](https://github.com/user-attachments/assets/f662c122-25a3-4d85-b42b-5e5f0edd5f74)

After following these steps, you will have mounted the projects directory inside the container.

Now, you must enter the `ort` container.
```bash
docker exec -it ort bash
```
And then follow these scenarios:
### Scenario 1: Start the server using the CPU EP to verify that the server was configured correctly.
```bash
cd /projects/trtsample
cargo run --release

cd /projects/loadtest
bash run.sh
```
The HTTP server must be successfully running.

### Scenario 2: Start the server using the TENSORRT EP.
```bash
cd /projects/trtsample
cargo run --release -F tensorrt

cd /projects/loadtest
bash run.sh
```
In my test, the HTTP server panics immediately after running the loadtest. I have set the default **GPU_ID = 1** in the file `/projects/trtsample/src/main.rs`, so it is expected to panic. However, if you change the **GPU_ID = 0**, the loadtest will run successfully.

### Scenario 2: Start the server using the TENSORRT EP + CUDA EP.
```bash
cd /projects/trtsample
cargo run --release -F tensorrt_cuda

cd /projects/loadtest
bash run.sh
```
You should change GPU_ID = 1 before running this test to observe that the issue has been resolved with the TensorRT EP.

#### NOTE: My machine is equipped with 8 NVIDIA RTX 4090 GPUs, and the driver version is 550.90.07.
![image](https://github.com/user-attachments/assets/08abc51e-3753-4efc-a419-e079f91955c2)

**Comment by chilo-ms** [comment]
Hi @dat58,

We recently found and [fixed ](https://github.com/microsoft/onnxruntime/pull/24010)a multithreading issue that running on GPU device > 0.
I think your issue is similar to a bug we found recently.

Feel free to try with this fix, it's just that the fix is not in any ORT official release now, but we plan to have it included in the ORT 1.21 patch release.

**Comment by dat58** [comment]
Hi @chilo-ms ,

I have tried with onnxruntime@1.21.0, and unfortunately, that did not solve my issue. Instead, it threw another error:

`2025-03-23T15:01:31.312155Z  WARN ort::environment: [2025-03-23 15:01:31   ERROR] 1: [reformat.cu::NCHWToNHWC::1798] Error Code 1: Cuda Runtime (invalid resource handle)

2025-03-23T15:01:31.312233Z  WARN ort::environment: Non-zero status code returned while running TRTKernel_graph_torch_jit_5455654249374742840_0 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_torch_jit_5455654249374742840_0_0' Status Message: TensorRT EP execution context enqueue failed.
`

**Comment by chilo-ms** [comment]
@dat58 
That fix is not in ORT 1.21.0, please try main.

**Comment by dat58** [comment]
Congrats @chilo-ms 

I’ve tested many times on the `main` branch with several models where I encountered this issue before, but now it’s resolved. Thanks a lot!

**Comment by chilo-ms** [comment]
Thanks for confirming!
FYI, we plan to have a patch release 1.21.1 which will include thix fix.
