### ISSUE TITLE
[Performance] TensorRT EP produce different inference results compared to CUDA/CPU

### ISSUE THREAD

**Issue by kylekam** [microsoft/onnxruntime#22354]
### Describe the issue

Inference results with YOLOv8 in C++ differ between TensorRT EP and CUDA EP. I'm unable to share all of the code because most of it is proprietary and it would require a lot of refactoring to make it viewable.

We use YOLOv8 as an object detector and results are satisfactory using CUDA EP, but we would like to speed up inference results using TensorRT.

https://github.com/microsoft/onnxruntime/issues/21457 may be related but their issues lie with a newer version of TensorRT, not 8.6.1.6

I've noticed some slightly different results from preprocesing steps by doing preprocessing on CPU vs GPU but nothing that should significantly affect the inference results. The output from YOLOv8 using TensorRT produces bounding boxes that are believable, but the confidence scores are terrible.

### To reproduce

Code snippet to initialize environment.
```
  // ORT Environment
  std::string instanceName{ "Image classifier" };
  auto ortEnv = std::make_unique<Ort::Env>(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, instanceName.c_str());
  Ort::SessionOptions sessionOptions;

  // Attempt to add to GPU
  int deviceCount;
  cudaGetDeviceCount(&deviceCount);
  const auto& api = Ort::GetApi();
  OrtTensorRTProviderOptionsV2* tensorrt_options = nullptr;
  try
  {
    Ort::ThrowOnError(api.CreateTensorRTProviderOptions(&tensorrt_options));
    std::vector<const char*> keys
    {
      "device_id",
      "trt_max_workspace_size",
      "trt_engine_cache_enable",
      "trt_engine_cache_path",
      "trt_timing_cache_enable",
      "trt_layer_norm_fp32_fallback",
      "trt_fp16_enable",
    };
    std::vector<const char*> values
    {
      "0",
      "24696061952",
      "1",
      "../models",
      "1",
      "1",
      "0",
    };
    Ort::ThrowOnError(api.UpdateTensorRTProviderOptions(tensorrt_options, keys.data(), values.data(), keys.size()));
    
    // Try setting lower priority for CUDA streams
    int priority_high;
    int priority_low;
    cudaStream_t stream_low;
    cudaDeviceGetStreamPriorityRange(&priority_low, &priority_high);
    cudaStreamCreateWithPriority(&stream_low, cudaStreamNonBlocking, priority_low);

    tensorrt_options->user_compute_stream = stream_low;
    tensorrt_options->has_user_compute_stream = true;
  }
  catch (Ort::Exception& e)
  {
    TrdDiags::Instance().error(__FUNCTION__, "Failing to update ORT Tensor RT provider options: %s ", e.what());
    return nullptr;
  }
  sessionOptions.AppendExecutionProvider_TensorRT_V2(*tensorrt_options);
  sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

  // Initialize session
  try
  {
    mSession = std::make_unique<Ort::Session>(*ortEnv, _modelFilePath.c_str(), sessionOptions);
  }
  catch (std::bad_alloc& e)
  {
    TrdDiags::Instance().error(__FUNCTION__, "Failed to initialize ORT session: %s ", e.what());
    return nullptr;
  }

  try
  {
    mIOBinding = std::make_unique<Ort::IoBinding>(mSession);
  }
  catch (std::bad_alloc& e)
  {
    TrdDiags::Instance().error(__FUNCTION__, "Failed to initialize IOBinding session: %s ", e.what());
    return nullptr;
  }

```

Snippet to run.
```
mIOBinding->BindInput(mInputNameString.c_str(), *inputTensors);
mIOBinding->BindOutput(mOutputNameString.c_str(), *outputTensors);
ortSession->Run(Ort::RunOptions{ nullptr }, *(mIOBinding));
```

### Platform

Windows

### OS Version

Windows 11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.2, CUDNN 8.9.2, TensorRT 8.6.1.6

### Is this a quantized model?

No

**Comment by tianleiwu** [comment]
See https://github.com/microsoft/onnxruntime/issues/21345#issuecomment-2245804574 for TRT fp16 accuracy.

**Comment by kylekam** [comment]
This issue is with FP32, but I appreciate your response. I'll see if there's anything I can use in that thread.

**Comment by tianleiwu** [comment]
You can try the TensorRT tool [polygraphy](https://github.com/NVIDIA/TensorRT/tree/release/10.4/tools/Polygraphy) to investigate the precision issue of TensorRT. 

See some examples: https://github.com/NVIDIA/TensorRT/tree/release/10.4/tools/Polygraphy/examples/cli/run/01_comparing_frameworks

**Comment by chilo-ms** [comment]
@kylekam
Did you try `trtexec` to see whether the output's confidence scores are terrible as well?
If yes, then the issue is coming from TRT. Otherwise, the issue might be from "old" TRT EP.

Since you can't share the model, it's hard for us to investigate, but we can still try several things for TRT EP:

- set NVIDIA_TF32_OVERRIDE=0
- disable graph optimization, sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
- In TRT 8.6, even though the model is FP32, TRT still builds lower precision for some layers if the perf is better. In TRT 10, the new [flag](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#strongly-typed-networks) is added to build strongly-typed network meaning TRT will stick to ONNX precision.

**Comment by chilo-ms** [comment]
Just wondering could you use the TRT 10 instead of the old TRT 8.6?
Even though we later root cause the issue, it's hard for us to fix the issue in the combination of ORT 1.15.1 + TRT 8.6

**Comment by kylekam** [comment]
After some investigation it turns out the issue came from a preprocessing step, so the issue wasn't with TensorRT itself.
