### ISSUE TITLE
onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Sigmoid node. CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by AndyFitia** [microsoft/onnxruntime#22441]
### Describe the issue

Greetings everyone.

Here is the error :
**[E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Sigmoid node. Name:'/model.0/act/Sigmoid' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device**

I am trying to inference on C++ my trained Yolo11 model after exporting it in onnx format,.
On CPU OnnxRuntime, I guess there are no issue (except my pc crashing due to cpu overload.
But when I run it on Cuda I got this error.

Thanks in advance.

### To reproduce

int main() {

    // > INIT ONNX Runtime
    const wchar_t* modelPath = L"Models/best_9_10_2024.onnx";
    Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "Default");
    Ort::SessionOptions sessionOptions;
    OrtCUDAProviderOptions cuda_options;

    sessionOptions.SetInterOpNumThreads(1);   // Controls threading between different operations
    sessionOptions.SetIntraOpNumThreads(1);   // Controls threading within a single operation
    // Optimization will take time and memory during startup
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
    Ort::Session session(nullptr);
    try {
        sessionOptions.AppendExecutionProvider_CUDA(cuda_options);
        session = Ort::Session(env, modelPath, sessionOptions); 
    }
    catch (Ort::Exception oe) {
        std::cout << "ONNX exception caught: " << oe.what() << ". Code: " << oe.GetOrtErrorCode() << ".\n";
        return -1;
    }
std::thread frameProcessingThread(FrameProcessing, std::ref(session));
...
}
void FrameProcessing(Ort::Session& session) {
    Ort::AllocatorWithDefaultOptions allocator;

    while (true) {
        cv::Mat blob = capturedFrameBuffer.GetFrame();
        if (blob.empty()) continue;

        std::array<int64_t, 4> inputShape = { 1, 3, 640, 640 };
        size_t inputTensorSize = 1 * 3 * 640 * 640;

        float* blobData = reinterpret_cast<float*>(blob.data);
        Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

        Ort::Value inputTensor = Ort::Value::CreateTensor<float>(
            memoryInfo, blobData, inputTensorSize, inputShape.data(), inputShape.size()
        );

        try {
            const char* inputNames[] = { "images" };
            const char* outputNames[] = { "output0" };
            auto outputTensors = session.Run(Ort::RunOptions{ nullptr }, inputNames, &inputTensor, 1, outputNames, 1);

            const float* outputData = outputTensors[0].GetTensorData<float>();
            // Process output data
        }
        catch (const Ort::Exception& e) {
            std::cerr << "ONNX Runtime exception: " << e.what() << std::endl;
        }
    }
}

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.4, CUDNN 9.1.0

**Comment by ReeRichard** [comment]
@AndyFitia  Hi, I am experiencing the same issue right now. What made you close this issue? Were you able to solve it?

**Comment by AndyFitia** [comment]
@ReeRichard, Hi
I directly used DirectML instead.

**Comment by AndyFitia** [comment]
> @AndyFitia  Hi, I am experiencing the same issue right now. What made you close this issue? Were you able to solve it?

@ReeRichard, hey again.
I forgot to specify that the real issue was that my GPU is not compatible, I guess it needs a gpu with a Compute Capability of 5.2 or 6.
My Gpu is a old one, NVIDIA Quadro M2000M

**Comment by ReeRichard** [comment]
> [@ReeRichard](https://github.com/ReeRichard), hey again. I forgot to specify that the real issue was that my GPU is not compatible, I guess it needs a gpu with a Compute Capability of 5.2 or 6. My Gpu is a old one, NVIDIA Quadro M2000M

@AndyFitia  Thanks for the response. That is probably a similar issue on my end. I am trying to run this on a Orin AGX which is limited to Cuda 11.4. I would assume that the model could be remodeled so that the missing kernel is run on the CPU but I guess the onnxruntime 1.12.1 does not have this feature yet our I need to modify it manually to do so. 🤷

**Comment by ReeRichard** [comment]
> [@ReeRichard](https://github.com/ReeRichard), hey again. I forgot to specify that the real issue was that my GPU is not compatible, I guess it needs a gpu with a Compute Capability of 5.2 or 6. My Gpu is a old one, NVIDIA Quadro M2000M

@AndyFitia 
I checked and the Cuda sigmoid function was added 2018 and is very simple. It should be available on any CUDA capable hardware basically. This is more likely a bug in the onnxruntime prior to v1.20.1 (where my model works fine on x86 GPU) as I am running an older version because of the nvcc not being able to cope with the cuda code from onnxruntime v1.20.1

**Comment by AndyFitia** [comment]
> > [@ReeRichard](https://github.com/ReeRichard), hey again. I forgot to specify that the real issue was that my GPU is not compatible, I guess it needs a gpu with a Compute Capability of 5.2 or 6. My Gpu is a old one, NVIDIA Quadro M2000M
> 
> @AndyFitia 
> I checked and the Cuda sigmoid function was added 2018 and is very simple. It should be available on any CUDA capable hardware basically. This is more likely a bug in the onnxruntime prior to v1.20.1 (where my model works fine on x86 GPU) as I am running an older version because of the nvcc not being able to cope with the cuda code from onnxruntime v1.20.1

@ReeRichard, there was also a time where I wanted to modify things to be compatible with GPU, but then it would transfer some computation to the CPU. I mean I didn't quite remember what I did, but the computation has been split up, meaning performance drop.
But as I said it has been a while since I ve done it, so I don't quite remember 

But DirectML was the only valuable solution for me.

**Comment by ReeRichard** [comment]
> But DirectML was the only valuable solution for me.

I used the TensorRT Provider now and it works great, thanks for the help
