### ISSUE TITLE
[Build] Cuda Execution Provider library is needed despite we only use TensoRT Execution provider

### ISSUE THREAD

**Issue by jcdatin** [microsoft/onnxruntime#22960]
### Describe the issue

There must be a way to build onnxruntime with tensorRt without the cuda execution provider and its cuda unused dependencies.
libonnxruntime_providers_cuda.so is big (220MB) and is dragging other big dependencies like libcufft or libcublas that we don't use in inference (another 400MB).

### Urgency

non blocking 

### Target platform

linux

### Build script

build.py

### Error / output

N/A

### Visual Studio Version

N/A

### GCC / Compiler Version

gcc11

**Comment by skottmckay** [comment]
https://github.com/microsoft/onnxruntime/blob/b930b4ab5bfd86eef3009ddfa52229e4b86c5e16/cmake/CMakeLists.txt#L90

Add this to your build command line `--cmake_extra_defines onnxruntime_CUDA_MINIMAL=ON`

**Comment by jcdatin** [comment]
thank you ! (I could not find it in build.py)
Trying this.

**Comment by jcdatin** [comment]
unfortunately this does not work , there is still cuda dependencies that caused compilation errors 
 [ 35%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/onnxruntime/onnxruntime/contrib_ops/cuda/bert/decoder_attention.cc.o
In file included from /onnxruntime/onnxruntime/contrib_ops/cuda/bert/attention.cc:5:
/onnxruntime/onnxruntime/core/providers/cuda/shared_inc/fpgeneric.h:22:8: error: ‘cublasStatus_t’ does not name a type; did you mean ‘cublasStrsv’?
   22 | **inline cublasStatus_t**
      |        ^~~~~~~~~~~~~~

**Comment by jcdatin** [comment]
same for 
Building CXX object CMakeFiles/onnxruntime_framework.dir/onnxruntime/onnxruntime/core/framework/config_options.cc (refers to cublas)
and a lot more ...

**Comment by skottmckay** [comment]
@gedoensmax is this expected? Not sure if there are other build settings required to use onnxruntime_CUDA_MINIMAL

**Comment by gedoensmax** [comment]
The cmake variable you mention Scott prunes all the dependencies from CUDA and makes the CUDA EP lib very small. Essentially it will only be able to execute memory copies and stresm management. 

This build scenario is also published at: https://github.com/NVIDIA/onnxruntime/releases

**Comment by poweiw** [comment]
Hello @jcdatin ! The error comes from some new code in 1.20 not guarded by the cuda minimal macro. The fix has been merged and hopefully will be included in the next patch release of ORT. https://github.com/microsoft/onnxruntime/pull/22751

**Comment by jcdatin** [comment]
> Hello [@jcdatin](https://github.com/jcdatin) ! The error comes from some new code in 1.20 not guarded by the cuda minimal macro. The fix has been merged and hopefully will be included in the next patch release of ORT. [#22751](https://github.com/microsoft/onnxruntime/pull/22751)

thx . happy to contribiye :-) Will use the next

**Comment by jcdatin** [comment]
tried again , but  got onnxrt compilation failure 
 [ 46%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/tmp/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc.o
In file included from /tmp/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.h:12,
                 from /tmp/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc:9:
/tmp/onnxruntime/onnxruntime/core/providers/cuda/shared_inc/cudnn_fe_call.h:9:10: fatal error: cudnn_frontend.h: No such file or directory
    9 | #include <cudnn_frontend.h>
      |          ^~~~~~~~~~~~~~~~~~

using TRT 10.7.23  Cudnn 9.6.0.74, ONNXRT 1.20.1 with gcc11
building command =

    CC=gcc-11 CXX=g++-11 ./build.sh \
    --skip_submodule_sync --nvcc_threads 2 \
    --config $ORT_BUILD_MODE --use_cuda \
    --cudnn_home /usr/local/cuda/lib64 \
    --cuda_home /usr/local/cuda/ \
    --use_tensorrt --tensorrt_home /usr/local/TensorRT \
    --build_shared_lib --parallel --skip_tests \
    --allow_running_as_root \
    --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=89" \
    --cmake_extra_defines onnxruntime_CUDA_MINIMAL=ON \
    --cmake_extra_defines "CMAKE_CUDA_HOST_COMPILER=/usr/bin/gcc-11"

-- ******** Summary ********
--   CMake version                     : 3.28.3
--   CMake command                     : /usr/bin/cmake
--   System                            : Linux
--   C++ compiler                      : /usr/bin/g++-11
--   C++ compiler version              : 11.3.0
--   CXX flags                         :  -ffunction-sections -fdata-sections -Wno-restrict  -DCPUINFO_SUPPORTED -Wnon-virtual-dtor
--   Build type                        : Release
--   Compile definitions               : ORT_ENABLE_STREAM;EIGEN_MPL2_ONLY;_GNU_SOURCE;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH                 : /tmp/onnxruntime/build/Linux/Release/installed
--   CMAKE_INSTALL_PREFIX              : /usr/local
--   CMAKE_MODULE_PATH                 : /tmp/onnxruntime/cmake/external
--
--   ONNX version                      : 1.16.1
--   ONNX NAMESPACE                    : onnx
--   ONNX_USE_LITE_PROTO               : ON
--   USE_PROTOBUF_SHARED_LIBS          : OFF
--   Protobuf_USE_STATIC_LIBS          : ON
--   ONNX_DISABLE_EXCEPTIONS           : OFF
--   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
--   ONNX_WERROR                       : OFF
--   ONNX_BUILD_TESTS                  : OFF
--   ONNX_BUILD_BENCHMARKS             : OFF
--   ONNX_BUILD_SHARED_LIBS            :
--   BUILD_SHARED_LIBS                 : OFF
--
--   Protobuf compiler                 :
--   Protobuf includes                 :
--   Protobuf libraries                :
--   BUILD_ONNX_PYTHON                 : OFF

**Comment by jcdatin** [comment]
added but is a duplicate to this issues since  when removing "--cmake_extra_defines onnxruntime_CUDA_MINIMAL=ON" flag, build is ok.

**Comment by chilo-ms** [comment]
Unfortunately, the https://github.com/microsoft/onnxruntime/pull/22751 that fixes the issue is not in ORT 1.20.1.
Please use ORT main or wait for the upcoming ORT 1.21 release.

**Comment by jcdatin** [comment]
Tried on main branch , build works . 
Unfortunately not only libonnxruntime_providers_cuda.so is built but there sis still a dependency of onnxruntime to it so e cannot remove it from deplyment.

2025-01-29 13:10:46.877679116 [E:onnxruntime:ivpSelectorInference, provider_bridge_ort.cc:2020 TryGetProviderInfo_CUDA] /tmp/onnxruntime/onnxruntime/core/session/provider_bridge_ort.cc:1679 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libonnxruntime_providers_cuda.so: cannot open shared object file: No such file or directory

Here is my build command 
RUN export no_proxy=${NO_PROXY} && \
    CC=gcc-11 CXX=g++-11 ./build.sh \
    --skip_submodule_sync \
    --nvcc_threads 2 \
    --config $ORT_BUILD_MODE \
    --use_cuda --cuda_home /usr/local/cuda/ \
    --cudnn_home /usr/local/cuda/lib64 \
    --use_tensorrt --tensorrt_home /usr/local/TensorRT \
    --build_shared_lib --parallel --skip_tests \
    --allow_running_as_root \
    --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=89" \
    --cmake_extra_defines onnxruntime_CUDA_MINIMAL=ON \
    --cmake_extra_defines "CMAKE_CUDA_HOST_COMPILER=/usr/bin/gcc-11"

yet when I try in my code to use Cuda EP , got the error 
2025-01-29 13:20:51.150632241 [I:onnxruntime:, cuda_execution_provider.cc:2682 GetCapability] CUDA kernel not found in registries for Op type: EPContext node name: EPContext

I am using cuda 12.2, cudnn 9.6.0.74 and TRT 10.7.0.23 with  gcc11 (Build does not work with gcc13 - max gcc accepted is gcc12 according to error traces.

**Comment by gedoensmax** [comment]
Ok it is wrong to say that you do not need the CUDA EP anymore. The library is still needed but upon running `ldd libonnxruntime_providers_cuda.so` you shouldd see that it does not longer rely on cuDNN and cuBlas etc. That significantly reduces the shipment size. Besides that the library itself should be much smaller.

**Comment by chilo-ms** [comment]
The CUDA_MINIMA build is only for TRT EP that we try to remove as much features as possible from CUDA EP but keep as less dependencies that TRT EP needs as possible. As Maxmilian mentioned above, libonnxruntime_providers_cuda.so is on longer relying on cuDNN and cuBlas etc.
You still need libonnxruntime_providers_cuda.so to run TRT EP, as it provides gpu allocator and stream management. But you can't run this CUDA EP (libonnxruntime_providers_cuda.so) as a standalone EP.

**Comment by jcdatin** [comment]
allright , now libonnxruntime_providers_cuda.so is 1MB with build flag -cmake_extra_defines "onnxruntime_CUDA_MINIMAL=ON", instead of previously 241MB : well done guys. I will test if any regression and we can close the case.

**Comment by jcdatin** [comment]
closing the case - see above
