### ISSUE TITLE
Inconsistent dependencies in libonnxruntime_providers_cuda.so file in x64-gpu binary release

### ISSUE THREAD

**Issue by kibae** [microsoft/onnxruntime#23953]
### Describe the issue

#22703 issue is reproduced again in version 1.21.0.

### To reproduce

```
$ ldd libonnxruntime_providers_cuda.so
        linux-vdso.so.1 (0x00007ffe4f6ee000)
        libcublasLt.so.11 => not found
        libcublas.so.11 => not found
        libcurand.so.10 => /usr/local/cuda/targets/x86_64-linux/lib/libcurand.so.10 (0x00007fc8fa600000)
        libcufft.so.10 => not found
        libcudart.so.11.0 => not found
        libcudnn.so.8 => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc900b1c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc900b17000)
        libnvrtc.so.11.2 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc900b12000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc8fa382000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc8fa299000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc900ae2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc8fa087000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc915339000)
```

### Platform

Linux

### OS Version

Any

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.21.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12

**Comment by amarin16** [comment]
Updated the [onnxruntime-linux-x64-gpu-1.21.0.tgz](https://github.com/microsoft/onnxruntime/releases/download/v1.21.0/onnxruntime-linux-x64-gpu-1.21.0.tgz) package in the GitHub release. Could you please verify if this fixes the issue for you?

**Comment by kibae** [comment]
I think the dependency issue is fixed, thanks. 👍 

```
$ ldd libonnxruntime_providers_cuda.so 
        linux-vdso.so.1 (0x00007ffc11975000)
        libcublasLt.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12 (0x00007f210e600000)
        libcublas.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.12 (0x00007f2107c00000)
        libcurand.so.10 => /usr/local/cuda/targets/x86_64-linux/lib/libcurand.so.10 (0x00007f2101600000)
        libcufft.so.11 => /usr/local/cuda/targets/x86_64-linux/lib/libcufft.so.11 (0x00007f20f0600000)
        libcudart.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12 (0x00007f20f0200000)
        libcudnn.so.9 => /lib/x86_64-linux-gnu/libcudnn.so.9 (0x00007f20efe00000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f212fe8b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f212fe86000)
        libnvrtc.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc.so.12 (0x00007f20ec000000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f212fe81000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f20ebd82000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2107b17000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f212fe51000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f20ebb70000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2144780000)
```
