### ISSUE TITLE
[Build] Cuda blackwell sm_120 Support

### ISSUE THREAD

**Issue by conleypri** [microsoft/onnxruntime#26177]
### Describe the issue

Requesting Onnxruntime support for Cuda blackwell sm_120, specifically running on NVIDIA GeForce RTX 5090 Laptop GPU with CUDA capability sm_120.

Dotnet Csharp:
Onnxruntime: 1.23.0
Onnxruntime-GenAI: 0.9.2

Error: **CUDA error cudaErrorInvalidPtx:a PTX JIT compilation failed**

### Target platform

Win64 - Cuda blackwell sm_120 - dotnet

### Build script

Running modified version of Onnxruntime-genai examples/csharp/HelloPhi.csproj with GPT-OSS model.

- Dotnet Run
Programs.cs preview:

```c#
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.ML.OnnxRuntimeGenAI;
using System.Text.Json;

// Hardcoded values for model path and execution provider
string modelPath = @"Onnx\Models\Microsoft\gpt-oss-20b-cuda-gpu\v1";
string executionProvider = "cuda";
bool interactive = true;

Console.WriteLine("-------------");
Console.WriteLine("Hello, GPT-OSS!");
Console.WriteLine("-------------");

Console.WriteLine("Model path: " + modelPath);
Console.WriteLine("Execution provider: " + executionProvider);
Console.WriteLine("Interactive: " + interactive);

using Config config = new Config(modelPath);
config.ClearProviders();
if (executionProvider != "cpu")
{
    config.AppendProvider(executionProvider);
}

Console.WriteLine("Using provider:" + executionProvider);
Model? modelRef = null;

try
{
    modelRef = new Model(config);
}
catch (Exception ex)
{
    Console.WriteLine($"Error loading model: {ex.Message}");
    return;
}

using Model model = modelRef;
Console.WriteLine("Model loaded.");
using Tokenizer tokenizer = new Tokenizer(model);

int minLength = 50;
int maxLength = 500;

static string GetPrompt(bool interactive)
{
    if (interactive)
    {
        Console.WriteLine("Prompt: (Use quit() to exit)");
        var line = Console.ReadLine();
        return line ?? string.Empty;
    }
    return "def is_prime(num):";
}

using GeneratorParams generatorParams = new GeneratorParams(model);
generatorParams.SetSearchOption("min_length", minLength);
generatorParams.SetSearchOption("max_length", maxLength);
using var tokenizerStream = tokenizer.CreateStream();
var prevTotalTokens = 0;

do
{
    string prompt = GetPrompt(interactive);
    if (string.IsNullOrEmpty(prompt))
    {
        continue;
    }
    if (string.Compare(prompt, "quit()", StringComparison.OrdinalIgnoreCase) == 0)
    {
        break;
    }

    // Apply the correct chat template and tokenize.
    // The chat template for gpt-oss-20b is provided by the tokenizer.
    // Use the role-based message format required by ApplyChatTemplate.
    var messages = new List<Dictionary<string, string>>
    {
        new Dictionary<string, string> { { "role", "user" }, { "content", prompt } }
    };
    string messagesJson = JsonSerializer.Serialize(messages);
    string formattedMessages = tokenizer.ApplyChatTemplate("", messagesJson, "", true);

    Console.WriteLine("\n--- Chat Template Applied ---\n" + formattedMessages + "\n----------------------------\n");

    var sequences = tokenizer.Encode(formattedMessages);

    // Check for valid token sequence length.
    if (sequences.NumSequences == 0)
    {
        Console.WriteLine("Error: The prompt resulted in an empty token sequence.");
        continue;
    }

    using var generator = new Generator(model, generatorParams);
    generator.AppendTokenSequences(sequences);

    var watch = System.Diagnostics.Stopwatch.StartNew();
    while (!generator.IsDone())
    {
        generator.GenerateNextToken();
        Console.Write(tokenizerStream.Decode(generator.GetSequence(0)[^1]));
    }
    Console.WriteLine();
    watch.Stop();

    var runTimeInSeconds = watch.Elapsed.TotalSeconds;
    var outputSequence = generator.GetSequence(0);
    var totalNewTokens = outputSequence.Length - prevTotalTokens;
    prevTotalTokens = outputSequence.Length;
    Console.WriteLine($"Streaming Tokens: {totalNewTokens} Time: {runTimeInSeconds:0.00} Tokens per second: {totalNewTokens / runTimeInSeconds:0.00}");
} while (interactive);
```

### Error / output

2025-09-26 09:19:39.1901015 [E:onnxruntime:onnxruntime-genai, sequential_executor.cc:572 onnxruntime::ExecuteKernel] Non-zero status code returned while running ReduceSum node. Name:'/model/attn_mask_reformat/attn_mask_subgraph/ReduceSum' Status Message: **CUDA error cudaErrorInvalidPtx:a PTX JIT compilation failed**
Unhandled exception. Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: Non-zero status code returned while running ReduceSum node. Name:'/model/attn_mask_reformat/attn_mask_subgraph/ReduceSum' Status Message: CUDA error cudaErrorInvalidPtx:a PTX JIT compilation failed
   at Microsoft.ML.OnnxRuntimeGenAI.Generator.AppendTokenSequences(Sequences sequences)
   at Program.<Main>$(String[] args) in Onnx\onnxruntime-genai\examples\csharp\HelloPhi\Program.cs:line 98

### Visual Studio Version

2022

### GCC / Compiler Version

1.23.0

**Comment by tianleiwu** [comment]
The current Onnxruntime GPU 1.23.0 nuget package only has PTX for sm_120 (We built PTX with 90a-real). For some reason, PTX JIT compilation failed for some kernel so it cannot run the model.

A walkaround is to build the GPU nuget package from source code with cuda 12.8. Here is an example build command line:
```
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

build.bat --cmake_generator "Visual Studio 17 2022" --config Release --build_dir build\cuda12 --build_wheel ^
          --parallel 4 --nvcc_threads 1 --build_shared_lib ^
          --use_cuda --cuda_version "12.8" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8" ^
          --cudnn_home "D:\cudnn\9.13.0.50_cuda12" ^
          --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=120" ^
          --build_nuget ^
          --skip_tests ^
          --use_binskim_compliant_compile_flags ^
          --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF ^
          --cmake_extra_defines FETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER
```

**Comment by conleypri** [comment]
That worked, thanks for the quick response! You and your team is doing a great job, keep it up!

**Comment by shirinebadi** [comment]
Hi. I'm also looking for onnx support for Cuda blackwell sm_120 for linux. Is it released?

**Comment by Nickuru** [comment]
SOLVED. Somehow managed Onnxruntime to work with sm_120 + CUDA Toolkit 13.

[ort-blackwell-build-guide.md](https://github.com/user-attachments/files/26477310/ort-blackwell-build-guide.md)

**Comment by chimney37** [comment]
btw, in case useful - was able to make it work on Linux (WSL2 actually), similar to Windows fix (CMAKE_CUDA_ARCHITECTURES=120), but maybe useful to call out GCC/glibc-specific issues, so here's the Linux side in case (this is just a local workaround). Confirmed it works at least for me - ONNX Runtime's graph-partitioning log: 221/231 nodes placed on CUDAExecutionProvider, and the whole thing executes successfully (rest of nodes went to CPU iiuc).
[onnxruntime-blackwell-linux-build-guide.md](https://github.com/user-attachments/files/30222198/onnxruntime-blackwell-linux-build-guide.md)

**Environment: Ubuntu 26.04, GCC 15.2.0, CUDA 13.0.88, RTX 5070 Ti, onnxruntime v1.24.2.**

```git clone --branch v1.24.2 --depth 1 https://github.com/microsoft/onnxruntime
cd onnxruntime
./build.sh --config Release --build --parallel 4 --nvcc_threads 1 \
  --build_shared_lib --use_cuda \
  --cuda_home /usr/local/cuda-13.0 --cudnn_home /usr \
  --skip_tests --cmake_generator Ninja \
  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=120 "CMAKE_CUDA_FLAGS=-D_GNU_SOURCE"
```

Three build-environment issues seems useful to call out in my case:

1. **glibc rsqrt/rsqrtf vs CUDA 13's math_functions.h** — incompatible exception specs between glibc's mathcalls.h declarations and CUDA 13's. Worked around with a header patch adding `noexcept(true)` to both declarations in .../crt/math_functions.h.

2. **pthread_cond_clockwait/pthread_mutex_clocklock undefined** — nvcc doesn't define _GNU_SOURCE by default, and libstdc++'s <mutex> needs it. Fixed with -D_GNU_SOURCE in CMAKE_CUDA_FLAGS.

3. **Default ninja target fails to compile** — pulls in onnxruntime_test_all, which fails on this GCC (-Werror=array-bounds on an unrelated test file). Built only needed target as workaround.
