### ISSUE TITLE
no kernel image is available for execution on the device [rtx 5090 laptop, wan2.2 animate, DWPreprocessor, onnxruntime-gpu]

### ISSUE THREAD

**Issue by igor-iki** [microsoft/onnxruntime#26181]
Hello. 
at first I've created thread on ComfyUI [https://github.com/comfyanonymous/ComfyUI/issues/10028](url)
There I found out that other people have the same issue and it's related to onnxruntime

**error**
` [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device`

So I have installed:
- latest pytorch with cu129 (tried also 128) 
- cuda toolkit
- latest onnxruntime-gpu
- latest nvidia gpu driver

Some people said that it's probably problem between onnxruntime and rtx50  GPU series

Comfy support also replied me with next words 

> means that ONNX Runtime’s GPU kernels are not fully compatible with your current GPU/driver/PyTorch setup.

`# ComfyUI Error Report
## Error Details
- **Node ID:** 233
- **Node Type:** DWPreprocessor
- **Exception Type:** onnxruntime.capi.onnxruntime_pybind11_state.Fail
- **Exception Message:** [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

## Stack Trace

  File "C:\comfy\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\comfy\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 91, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution, xinsr_stick_scaling=scale_stick_for_xinsr_cn)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ~~~~~^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 266, in __call__
    poses = self.detect_poses(input_image)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 255, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 93, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})

  File "c:\comfy\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 275, in run
    return self._sess.run(output_names, input_feed, run_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.60
- **Arguments:** main.py --gpu
- **OS:** nt
- **Python Version:** 3.13.7 (main, Sep 18 2025, 19:43:45) [MSC v.1944 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0+cu129
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25650855936
  - **VRAM Free:** 24151851008
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-09-26T07:01:12.819087 - [START] Security scan2025-09-26T07:01:12.819108 - 
2025-09-26T07:01:13.588117 - [DONE] Security scan2025-09-26T07:01:13.588128 - 
2025-09-26T07:01:13.747649 - ## ComfyUI-Manager: installing dependencies done.2025-09-26T07:01:13.747852 - 
2025-09-26T07:01:13.747967 - ** ComfyUI startup time:2025-09-26T07:01:13.748008 -  2025-09-26T07:01:13.748049 - 2025-09-26 07:01:13.7472025-09-26T07:01:13.748079 - 
2025-09-26T07:01:13.748115 - ** Platform:2025-09-26T07:01:13.748145 -  2025-09-26T07:01:13.748210 - Windows2025-09-26T07:01:13.748303 - 
2025-09-26T07:01:13.748360 - ** Python version:2025-09-26T07:01:13.748408 -  2025-09-26T07:01:13.748455 - 3.13.7 (main, Sep 18 2025, 19:43:45) [MSC v.1944 64 bit (AMD64)]2025-09-26T07:01:13.748487 - 
2025-09-26T07:01:13.748518 - ** Python executable:2025-09-26T07:01:13.748548 -  2025-09-26T07:01:13.748577 - c:\comfy\.venv\Scripts\python.exe2025-09-26T07:01:13.748604 - 
2025-09-26T07:01:13.748633 - ** ComfyUI Path:2025-09-26T07:01:13.748661 -  2025-09-26T07:01:13.748689 - C:\comfy\ComfyUI2025-09-26T07:01:13.748717 - 
2025-09-26T07:01:13.748746 - ** ComfyUI Base Folder Path:2025-09-26T07:01:13.748773 -  2025-09-26T07:01:13.748800 - C:\comfy\ComfyUI2025-09-26T07:01:13.748828 - 
2025-09-26T07:01:13.748856 - ** User directory:2025-09-26T07:01:13.748883 -  2025-09-26T07:01:13.748911 - C:\comfy\ComfyUI\user2025-09-26T07:01:13.748938 - 
2025-09-26T07:01:13.748966 - ** ComfyUI-Manager config path:2025-09-26T07:01:13.748993 -  2025-09-26T07:01:13.749021 - C:\comfy\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-09-26T07:01:13.749048 - 
2025-09-26T07:01:13.749078 - ** Log path:2025-09-26T07:01:13.749116 -  2025-09-26T07:01:13.749257 - C:\comfy\ComfyUI\user\comfyui.log2025-09-26T07:01:13.749296 - 
2025-09-26T07:01:14.456408 - 
Prestartup times for custom nodes:
2025-09-26T07:01:14.456678 -    1.9 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2025-09-26T07:01:14.456771 - 
2025-09-26T07:01:15.550851 - Checkpoint files will always be loaded safely.
2025-09-26T07:01:15.656871 - Total VRAM 24463 MB, total RAM 64943 MB
2025-09-26T07:01:15.657138 - pytorch version: 2.10.0.dev20250924+cu130
2025-09-26T07:01:15.657642 - Set vram state to: NORMAL_VRAM
2025-09-26T07:01:15.658045 - Device: cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU : cudaMallocAsync
2025-09-26T07:01:16.328821 - Using pytorch attention
2025-09-26T07:01:17.445767 - Python version: 3.13.7 (main, Sep 18 2025, 19:43:45) [MSC v.1944 64 bit (AMD64)]
2025-09-26T07:01:17.446059 - ComfyUI version: 0.3.60
2025-09-26T07:01:17.466881 - ComfyUI frontend version: 1.26.13
2025-09-26T07:01:17.468020 - [Prompt Server] web root: c:\comfy\.venv\Lib\site-packages\comfyui_frontend_package\static
2025-09-26T07:01:18.488194 - ComfyUI-GGUF: Allowing full torch compile
2025-09-26T07:01:18.520134 - ### Loading: ComfyUI-Manager (V3.37)
2025-09-26T07:01:18.520741 - [ComfyUI-Manager] network_mode: public
2025-09-26T07:01:18.793401 - ### ComfyUI Version: v0.3.60-5-gce4cb238 | Released on '2025-09-25'
2025-09-26T07:01:19.170236 - �[36;20m[C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts�[0m
2025-09-26T07:01:19.170550 - �[36;20m[C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False�[0m
2025-09-26T07:01:19.170746 - �[36;20m[C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']�[0m
2025-09-26T07:01:19.242499 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-09-26T07:01:19.263958 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-09-26T07:01:19.300041 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-09-26T07:01:19.344397 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-09-26T07:01:19.424334 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-09-26T07:01:19.428320 - DWPose: Onnxruntime with acceleration providers detected2025-09-26T07:01:19.428437 - 
2025-09-26T07:01:19.434691 - 
Import times for custom nodes:
2025-09-26T07:01:19.435105 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\websocket_image_save.py
2025-09-26T07:01:19.435244 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2025-09-26T07:01:19.435311 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-GGUF
2025-09-26T07:01:19.435376 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\comfyui-kjnodes
2025-09-26T07:01:19.435435 -    0.3 seconds: C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux
2025-09-26T07:01:19.435492 -    0.6 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2025-09-26T07:01:19.435533 - 
2025-09-26T07:01:20.006308 - Context impl SQLiteImpl.
2025-09-26T07:01:20.006558 - Will assume non-transactional DDL.
2025-09-26T07:01:20.007402 - No target revision found.
2025-09-26T07:01:20.015579 - Starting server

2025-09-26T07:01:20.015969 - To see the GUI go to: http://127.0.0.1:8188
2025-09-26T07:01:24.189744 - FETCH ComfyRegistry Data: 5/982025-09-26T07:01:24.189867 - 
2025-09-26T07:01:24.247447 - got prompt
2025-09-26T07:01:26.206881 - Using pytorch attention in VAE
2025-09-26T07:01:26.207921 - Using pytorch attention in VAE
2025-09-26T07:01:26.359805 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-09-26T07:01:28.379927 - FETCH ComfyRegistry Data: 10/982025-09-26T07:01:28.380050 - 
2025-09-26T07:01:33.183183 - FETCH ComfyRegistry Data: 15/982025-09-26T07:01:33.183360 - 
2025-09-26T07:01:36.514022 - [{'startX': 70.47225047713542, 'startY': 828.8878984691643}]2025-09-26T07:01:36.514222 - 
2025-09-26T07:01:36.535651 - c:\comfy\.venv\Lib\site-packages\torch\backends\__init__.py:46: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:85.)
  self.setter(val)
2025-09-26T07:01:36.535878 - model_path: 2025-09-26T07:01:36.535983 -  2025-09-26T07:01:36.536113 - C:\comfy\ComfyUI\models\sam2\sam2_hiera_base_plus.safetensors2025-09-26T07:01:36.536217 - 
2025-09-26T07:01:36.536345 - Using model config: C:\comfy\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2_configs\sam2_hiera_b+.yaml2025-09-26T07:01:36.536432 - 
2025-09-26T07:01:37.284693 - Resizing to model input image size: 2025-09-26T07:01:37.284937 -  2025-09-26T07:01:37.285115 - 10242025-09-26T07:01:37.285235 - 
2025-09-26T07:01:37.356343 - FETCH ComfyRegistry Data: 20/982025-09-26T07:01:37.361040 - 
2025-09-26T07:01:37.662639 - combined labels: 2025-09-26T07:01:37.662944 -  2025-09-26T07:01:37.663571 - [1. 1. 1. 1.]2025-09-26T07:01:37.663758 - 
2025-09-26T07:01:37.663869 - combined labels shape: 2025-09-26T07:01:37.663987 -  2025-09-26T07:01:37.664097 - (4,)2025-09-26T07:01:37.664157 - 
2025-09-26T07:01:41.690041 - 
propagate in video:  14%|██████████████▊                                                                                              | 60/442 [00:03<00:21, 18.11it/s]2025-09-26T07:01:41.770976 - FETCH ComfyRegistry Data: 25/982025-09-26T07:01:41.771129 - 
2025-09-26T07:01:45.853957 - 
propagate in video:  30%|████████████████████████████████▋                                                                           | 134/442 [00:07<00:17, 17.84it/s]2025-09-26T07:01:45.948222 - FETCH ComfyRegistry Data: 30/982025-09-26T07:01:45.948377 - 
2025-09-26T07:01:49.881090 - 
propagate in video:  47%|██████████████████████████████████████████████████▎                                                         | 206/442 [00:11<00:12, 18.29it/s]2025-09-26T07:01:49.949703 - FETCH ComfyRegistry Data: 35/982025-09-26T07:01:49.949804 - 
2025-09-26T07:01:55.996975 - 
propagate in video:  72%|█████████████████████████████████████████████████████████████████████████████▋                              | 318/442 [00:17<00:06, 18.16it/s]2025-09-26T07:01:56.030460 - FETCH ComfyRegistry Data: 40/982025-09-26T07:01:56.030577 - 
2025-09-26T07:02:00.386359 - 
propagate in video:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████▏          | 398/442 [00:21<00:02, 18.86it/s]2025-09-26T07:02:00.434087 - FETCH ComfyRegistry Data: 45/982025-09-26T07:02:00.434212 - 
2025-09-26T07:02:02.778805 - 
propagate in video: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [00:24<00:00, 18.66it/s]2025-09-26T07:02:02.779110 - 
propagate in video: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [00:24<00:00, 18.13it/s]2025-09-26T07:02:02.779267 - 
2025-09-26T07:02:05.329476 - FETCH ComfyRegistry Data: 50/982025-09-26T07:02:05.329664 - 
2025-09-26T07:02:09.369790 - FETCH ComfyRegistry Data: 55/982025-09-26T07:02:09.370384 - 
2025-09-26T07:02:14.425870 - FETCH ComfyRegistry Data: 60/982025-09-26T07:02:14.425967 - 
2025-09-26T07:02:18.501958 - FETCH ComfyRegistry Data: 65/982025-09-26T07:02:18.502077 - 
2025-09-26T07:02:23.684503 - FETCH ComfyRegistry Data: 70/982025-09-26T07:02:23.684633 - 
2025-09-26T07:02:28.030673 - FETCH ComfyRegistry Data: 75/982025-09-26T07:02:28.030783 - 
2025-09-26T07:02:32.199516 - FETCH ComfyRegistry Data: 80/982025-09-26T07:02:32.199801 - 
2025-09-26T07:02:36.426980 - FETCH ComfyRegistry Data: 85/982025-09-26T07:02:36.427239 - 
2025-09-26T07:02:40.675295 - FETCH ComfyRegistry Data: 90/982025-09-26T07:02:40.675620 - 
2025-09-26T07:02:44.871459 - FETCH ComfyRegistry Data: 95/982025-09-26T07:02:44.872162 - 
2025-09-26T07:02:47.844766 - FETCH ComfyRegistry Data [DONE]2025-09-26T07:02:47.845517 - 
2025-09-26T07:02:48.000425 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-09-26T07:02:48.026021 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-09-26T07:02:48.026243 - 2025-09-26T07:02:48.144471 -  [DONE]2025-09-26T07:02:48.144715 - 
2025-09-26T07:02:48.220823 - [ComfyUI-Manager] All startup tasks have been completed.
2025-09-26T07:02:57.903082 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v\DWPose\yolox_l.onnx2025-09-26T07:02:57.903302 - 
2025-09-26T07:02:57.903779 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16\DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt2025-09-26T07:02:57.903855 - 
2025-09-26T07:02:57.903905 - 
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation2025-09-26T07:02:57.903950 - 
2025-09-26T07:02:57.904014 - DWPose: Caching ONNXRuntime session yolox_l.onnx...2025-09-26T07:02:57.904044 - 
2025-09-26T07:03:01.888697 - DWPose: Caching TorchScript module dw-ll_ucoco_384_bs5.torchscript.pt on ...2025-09-26T07:03:01.889139 - 
2025-09-26T07:03:02.174807 - !!! Exception during processing !!! [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
2025-09-26T07:03:02.179358 - Traceback (most recent call last):
  File "C:\comfy\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\comfy\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 91, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution, xinsr_stick_scaling=scale_stick_for_xinsr_cn)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ~~~~~^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 266, in __call__
    poses = self.detect_poses(input_image)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 255, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 93, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})
  File "c:\comfy\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 275, in run
    return self._sess.run(output_names, input_feed, run_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

2025-09-26T07:03:02.182351 - Prompt executed in 97.93 seconds
2025-09-26T07:03:57.489130 - got prompt
2025-09-26T07:03:57.507787 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v\DWPose\yolox_l.onnx2025-09-26T07:03:57.507894 - 
2025-09-26T07:03:57.508113 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16\DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt2025-09-26T07:03:57.508537 - 
2025-09-26T07:03:57.508755 - 
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation2025-09-26T07:03:57.509589 - 
2025-09-26T07:03:57.531348 - !!! Exception during processing !!! [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
2025-09-26T07:03:57.532794 - Traceback (most recent call last):
  File "C:\comfy\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\comfy\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 91, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution, xinsr_stick_scaling=scale_stick_for_xinsr_cn)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ~~~~~^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 266, in __call__
    poses = self.detect_poses(input_image)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 255, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 93, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})
  File "c:\comfy\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 275, in run
    return self._sess.run(output_names, input_feed, run_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

2025-09-26T07:03:57.536189 - Prompt executed in 0.04 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

Workflow too large. Please manually upload the workflow from local file system.


## Additional Context
(Please add any additional context or steps to reproduce the error here)`

**Comment by spotya699-dev** [comment]
same issue, 5090, latest drivers, PyTorch Version: 2.8.0+cu128, python version is 3.12.10

**Comment by snnn** [comment]
So, if I understand correctly,  several custom nodes and specific models rely on ONNX Runtime for their operation. Did the problem exist before onnxruntime 1.23.0 was released?  How was onnxruntime-gpu installed on the machine? Now the package is hosted on pypi but we are face storage problems. I am consider moving the package to a self-hosted place, then we can enable more CUDA hardware support. 5090 use CUDA compute arch 12.0 which is not built in the onnxruntime package.

**Comment by snnn** [comment]
The package only has archs of 52-real,61-real,75-real,86-real,89-real and 90a-virtual due to pypi size limitation.

**Comment by snnn** [comment]
I checked the original issue. It seems that [DWPose](https://github.com/IDEA-Research/DWPose)'s controlnet preprocessor uses ONNX Runtime

**Comment by igor-iki** [comment]
> The package only has archs of 52-real,61-real,75-real,86-real,89-real and 90a-virtual due to pypi size limitation.
> So, if I understand correctly, several custom nodes and specific models rely on ONNX Runtime for their operation. Did the problem exist before onnxruntime 1.23.0 was released? How was onnxruntime-gpu installed on the machine? Now the package is hosted on pypi but we are face storage problems. I am consider moving the package to a self-hosted place, then we can enable more CUDA hardware support. 5090 use CUDA compute arch 12.0 which is not built in the onnxruntime package.

thanks for answers. please tell what is solution before yoi move package to a self hosted place?

**Comment by igor-iki** [comment]
git clone and build own whl for nvidia tensorRT RTX? will it compile arch 120? can you help with right CMD?

**Comment by snnn** [comment]
See: https://onnxruntime.ai/docs/build/eps.html#cuda

You need to download CUDA SDK 12.8(or later) and cudnn 9.5.  You also need to add "--cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=120" to the build command, since according to https://developer.nvidia.com/cuda-gpus 5090 uses CUDA compute arch 12.0

**Comment by igor-iki** [comment]
i have compiled with cuda 13.0 and all works! thanks.

**Comment by spotya699-dev** [comment]
I've never worked with build. Can you share the build? I have downloaded cudnn-cu12 v9.13.1.26 for 12.8 CUDA but not sure what to do next :/

**Comment by spotya699-dev** [comment]
welp, I tried to build and while doing the tests I got one failed: [  FAILED  ] CApiTest.custom_op_set_input_memory_type (6:onnxruntime_shared_lib_test). Not sure what causes that. I've got cuda 12.8, cudnn 9.5, VS2022 etc. PATHS were added. Can I still build the whl? 

I wish someone could share his .whl so we can just install the prerequesites of that wheel while that publish a working onnx for 5090. :(

**Comment by igor-iki** [comment]
> welp, I tried to build and while doing the tests I got one failed: [ FAILED ] CApiTest.custom_op_set_input_memory_type (6:onnxruntime_shared_lib_test). Not sure what causes that. I've got cuda 12.8, cudnn 9.5, VS2022 etc. PATHS were added. Can I still build the whl?
> 
> I wish someone could share his .whl so we can just install the prerequesites of that wheel while that publish a working onnx for 5090. :(

ok, my whl for pytorch2.10 + cuda13.
[https://limewire.com/d/ygJnp#sUrQgNBaRW](https://limewire.com/d/ygJnp#sUrQgNBaRW)

**Comment by spotya699-dev** [comment]
> > welp, I tried to build and while doing the tests I got one failed: [ FAILED ] CApiTest.custom_op_set_input_memory_type (6:onnxruntime_shared_lib_test). Not sure what causes that. I've got cuda 12.8, cudnn 9.5, VS2022 etc. PATHS were added. Can I still build the whl?
> > I wish someone could share his .whl so we can just install the prerequesites of that wheel while that publish a working onnx for 5090. :(
> 
> ok, my whl for pytorch2.10 + cuda13. https://limewire.com/d/ygJnp#sUrQgNBaRW

Thanks I will give it a try.
I didn't know if I should update to higher version of pytorch after 2.8 with 5090. I assume I won't have any problem with comfyui with cuda13 as well.

**Comment by spotya699-dev** [comment]
> > welp, I tried to build and while doing the tests I got one failed: [ FAILED ] CApiTest.custom_op_set_input_memory_type (6:onnxruntime_shared_lib_test). Not sure what causes that. I've got cuda 12.8, cudnn 9.5, VS2022 etc. PATHS were added. Can I still build the whl?
> > I wish someone could share his .whl so we can just install the prerequesites of that wheel while that publish a working onnx for 5090. :(
> 
> ok, my whl for pytorch2.10 + cuda13. https://limewire.com/d/ygJnp#sUrQgNBaRW

I've reinstalled pytorch 2.10 and cuda13. I reinstalled requirements but the latest numpy (or atleast the one that came with pytorch2.10) didnt seem to work with the latest versions for custom nodes and other stuffs. Were you using a numpy v1.x? And when I update comfyui it tries to reinstall torch2.8. Sooo I cannot update everything until 2.10 becomes stable version? I had to install nympy­<2 but still gives me incompatiblities. Are you still using Sageattention 2.2? maybe it conflicts since it uses diff pytorch/cuda128?

Maybe can you clear the things up for me or im missing something again lol

**Comment by igor-iki** [comment]
u need to install with --no-deps to avoid updating numpy

**Comment by pintarj** [comment]
i had the same problem with mine 5090, simply downgrading the `onnxruntime-gpu` to version 1.22 solved my situation

**Comment by spotya699-dev** [comment]
> i had the same problem with mine 5090, simply downgrading the `onnxruntime-gpu` to version 1.22 solved my situation

Which issue? Sry I see some in here xD

**Comment by snnn** [comment]
So this is related to the change #26002 ?

**Comment by snnn** [comment]
In the PR we didn't change any setting for onnxruntime-gpu Windows package. So, I am wondering ...

**Comment by PaulDallas72** [comment]
> i had the same problem with mine 5090, simply downgrading the `onnxruntime-gpu` to version 1.22 solved my situation

Fixed my 5090 issue also.  Thanks pintarj and Github.

**Comment by FurkanGozukara** [comment]
> In the PR we didn't change any setting for onnxruntime-gpu Windows package. So, I am wondering ...

I have exactly same issue

1.22 fixed and 1.23 failing 

https://github.com/microsoft/onnxruntime/issues/26221

**Comment by RYOO87** [comment]
> i had the same problem with mine 5090, simply downgrading the `onnxruntime-gpu` to version 1.22 solved my situation

How to downgrade 'onnxruntime-gpu'?

**Comment by ShakieVan** [comment]
> > i had the same problem with mine 5090, simply downgrading the `onnxruntime-gpu` to version 1.22 solved my situation
> 
> How to downgrade 'onnxruntime-gpu'?

REM 1) ONNX GPU/CPU-Pakete entfernen
E:\KI\ComfyUI_windows_portable\python_embeded\python.exe -m pip uninstall -y onnxruntime-gpu onnxruntime

REM 2) DirectML-Backend installieren
E:\KI\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade onnxruntime-directml

**Comment by Matte2686** [comment]
use CPU only for this node...

Open the command prompt in your folder
Go to

.../ComfyUI_windows_portable/python_embeded

open cmd

Run these commands:

.\python.exe -m pip install --upgrade pip setuptools wheel
.\python.exe -m pip uninstall -y onnxruntime-gpu onnxruntime-directml onnxruntime
.\python.exe -m pip install "onnxruntime>=1.20.0,<1.24"


(If you prefer a specific version, for example: onnxruntime==1.23.1.)

Restart ComfyUI and check In the startup log, you should see that DWPreprocessor / ONNX Runtime is using CPUExecutionProvider

**Comment by markdalias** [comment]
for anyone stumbling upon this struggling with dwpose or other controlnets with onnx on blackwell GPUs, here are your options that worked for me:
- uninstall onnxruntime-gpu and install only onnxruntime, which will use CPU (slow)
- use .pth models instead of .onnx models
- install onnxruntime-gpu==1.22.0

I'm not sure but there may be a bug introduced in 1.23.0

**Comment by snnn** [comment]
We published a new release. Please try it:
```
pip install onnxruntime-gpu==1.23.2
```

**Comment by ShakieVan** [comment]
> We published a new release. Please try it:
> 
> ```
> pip install onnxruntime-gpu==1.23.2
> ```

Works for me with RTX 5090 now.
Thanks a lot!

**Comment by PaulDallas72** [comment]
Thanks for the recent update Team Onnx.  Now DWpose and all the other Onnx runtime dependent apps run perfectly on my Asus 5090 and 9950x3d!

**Comment by FurkanGozukara** [comment]
> We published a new release. Please try it:
> 
> ```
> pip install onnxruntime-gpu==1.23.2
> ```

my pip doesnt show it

python 3.10.11

<img width="1727" height="367" alt="Image" src="https://github.com/user-attachments/assets/28085faf-de0b-4e14-a002-aa7d3993fd26" />
