### ISSUE TITLE
CUDA failure 700: an illegal memory access was encountered

### ISSUE THREAD

**Issue by rscguo** [microsoft/onnxruntime#26312]
onnxruntime api version is onnxruntime-win-x64-gpu-1.23.0.

win 10, cuda 12.0

if use cuda session option and cuda input tensor:

```
    Ort::Env env(ORT_LOGGING_LEVEL_ERROR, "demo");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_BASIC);
    OrtCUDAProviderOptions options;
    options.device_id = 0;
    session_options.AppendExecutionProvider_CUDA(options);
    Ort::Session session(env, 'xxx.onnx', session_options);
    size_t num_input_nodes = session.GetInputCount();
    size_t num_output_nodes = session.GetOutputCount();
    std::cout << "num_nodes: " << num_input_nodes << ", " << num_output_nodes << std::endl;
    std::vector<std::string> input_node_namestr = session.GetInputNames();
    std::vector<std::string> output_node_namestr = session.GetOutputNames();
    std::vector<const char*> input_node_names;
    std::vector<const char*> output_node_names;
    for (int i = 0; i < num_input_nodes; i++)
    {
        input_node_names.push_back(input_node_namestr[i].c_str());
    }
    for (int i = 0; i < num_output_nodes; i++)
    {
        output_node_names.push_back(output_node_namestr[i].c_str());
    }
    Ort::MemoryInfo memory_info("Cuda", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemTypeDefault);
    std::vector<float> tensor_values = { 1.0f, 2.0f, 3.0f };
    std::vector<int64_t> node_dims = { 3 };
    Ort::Value tensor = Ort::Value::CreateTensor<float>(
        memory_info,
        tensor_values.data(),
        tensor_values.size(),
        node_dims.data(),
        node_dims.size()
    );
    std::vector<Ort::Value> input_tensors;
    input_tensors.push_back(std::move(tensor));
    std::vector<Ort::Value> output_tensors = session.Run(
        Ort::RunOptions{ nullptr },
        input_node_names.data(),
        input_tensors.data(),
        num_input_nodes,
        output_node_names.data(),
        //output_tensors.data(),
        num_output_nodes
    );
    std::cout << "output_tensors: " << output_tensors.size() << std::endl;
```

and then the error occurred:

` [E:onnxruntime:demo, cuda_call.cc:123 onnxruntime::CudaCall] CUDA failure 700: an illegal memory access was encountered ; GPU=0 ; hostname=DESKTOP-0KEQI56 ; file=E:\_work\1\s\onnxruntime\core\providers\cuda\gpu_data_transfer.cc ; line=97 ; expr=cudaMemcpyAsy`

**Comment by tianleiwu** [comment]
Here is analysis from AI (It might not be correct):
----------------------------

The error `CUDA failure 700: an illegal memory access was encountered` is happening because there's a mismatch between where your tensor data actually resides (CPU) and where you're telling ONNX Runtime it resides (GPU).

You are creating a tensor with a pointer to CPU memory but labeling it as if it's already on the GPU.

-----

### The Problem

The core of the issue is in these two lines:

```cpp
// This says "The tensor data I'm about to describe is on the GPU."
Ort::MemoryInfo memory_info("Cuda", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemTypeDefault);

// This provides a pointer to data that is actually on the CPU (in std::vector).
Ort::Value tensor = Ort::Value::CreateTensor<float>(
    memory_info,           // You promised GPU memory...
    tensor_values.data(),  // ...but provided a CPU pointer.
    tensor_values.size(),
    node_dims.data(),
    node_dims.size()
);
```

When you call `session.Run()`, ONNX Runtime sees the tensor is flagged as being on the GPU, so it passes the pointer directly to a CUDA kernel. The kernel, running on the GPU, tries to access this address, which is a CPU memory address, resulting in an "illegal memory access" error. `CreateTensor` does **not** automatically copy the data to the device; it simply wraps the pointer you give it.

-----

### The Solution

The correct approach is to create the tensor on the **CPU** and let ONNX Runtime handle the transfer to the GPU for you. Since you've configured a CUDA execution provider, ONNX Runtime will see that the model needs the data on the GPU and will perform the `cudaMemcpy` automatically.

You just need to change how you create your `MemoryInfo`.

```cpp
// CORRECTED CODE
// Key Change 1: Create a MemoryInfo object that describes CPU memory.
Ort::MemoryInfo memory_info = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemTypeDefault);

std::vector<float> tensor_values = { 1.0f, 2.0f, 3.0f };
std::vector<int64_t> node_dims = { 3 };

// Key Change 2: Now, CreateTensor correctly wraps the CPU data pointer.
Ort::Value tensor = Ort::Value::CreateTensor<float>(
    memory_info,
    tensor_values.data(),
    tensor_values.size(),
    node_dims.data(),
    node_dims.size()
);
```

By correctly identifying the input tensor's location as the CPU, you allow ONNX Runtime's internal logic to manage the Host-to-Device data transfer before executing the model.

-----

### Complete Corrected Code

Here is your full code snippet with the necessary correction.

```cpp
#include <onnxruntime_cxx_api.h>
#include <iostream>
#include <vector>

int main() {
    Ort::Env env(ORT_LOGGING_LEVEL_ERROR, "demo");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_BASIC);
    
    OrtCUDAProviderOptions options;
    options.device_id = 0;
    session_options.AppendExecutionProvider_CUDA(options);
    
    // Use a valid model path
    const char* model_path = "xxx.onnx"; 
    Ort::Session session(env, model_path, session_options);

    size_t num_input_nodes = session.GetInputCount();
    size_t num_output_nodes = session.GetOutputCount();
    std::cout << "Input Nodes: " << num_input_nodes << ", Output Nodes: " << num_output_nodes << std::endl;

    // Use allocator for dynamic memory management of names
    Ort::AllocatorWithDefaultOptions allocator;
    std::vector<const char*> input_node_names;
    std::vector<std::string> input_node_names_str;
    for (size_t i = 0; i < num_input_nodes; i++) {
        char* name = session.GetInputName(i, allocator);
        input_node_names.push_back(name);
        input_node_names_str.push_back(name); // For easier management
    }

    std::vector<const char*> output_node_names;
    std::vector<std::string> output_node_names_str;
    for (size_t i = 0; i < num_output_nodes; i++) {
        char* name = session.GetOutputName(i, allocator);
        output_node_names.push_back(name);
        output_node_names_str.push_back(name); // For easier management
    }

    // --- KEY CORRECTION IS HERE ---
    // 1. Create a MemoryInfo object that describes CPU memory.
    // This correctly states where `tensor_values` is located.
    Ort::MemoryInfo memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

    std::vector<float> tensor_values = { 1.0f, 2.0f, 3.0f };
    std::vector<int64_t> node_dims = { 3 }; // Make sure this shape matches your model's input

    // 2. Create the tensor on the CPU.
    Ort::Value input_tensor = Ort::Value::CreateTensor<float>(
        memory_info,
        tensor_values.data(),
        tensor_values.size(),
        node_dims.data(),
        node_dims.size()
    );
    
    std::vector<Ort::Value> input_tensors;
    input_tensors.push_back(std::move(input_tensor));

    // ONNX Runtime will automatically copy the input_tensors to the GPU before running.
    std::vector<Ort::Value> output_tensors = session.Run(
        Ort::RunOptions{ nullptr },
        input_node_names.data(),
        input_tensors.data(),
        num_input_nodes,
        output_node_names.data(),
        num_output_nodes
    );

    std::cout << "Successfully received " << output_tensors.size() << " output tensor(s)." << std::endl;

    // Free the memory allocated by GetInputName/GetOutputName
    for(auto name : input_node_names) {
        allocator.Free(name);
    }
    for(auto name : output_node_names) {
        allocator.Free(name);
    }

    return 0;
}
```

**Comment by rscguo** [comment]
My really destination is to get the output tensor on Cuda. Because my another cuda code will use the output tensor again!
Actually, I have tried to create input tensor on Cpu memory and run the session on Cuda, but the output tensor is still on Cpu.
The code is just like:

    Ort::Env env(ORT_LOGGING_LEVEL_ERROR, "demo");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_BASIC);
    OrtCUDAProviderOptions options;
    options.device_id = 0;
    session_options.AppendExecutionProvider_CUDA(options);
    Ort::Session session(env, 'xxx.onnx', session_options);
    size_t num_input_nodes = session.GetInputCount();
    size_t num_output_nodes = session.GetOutputCount();
    std::cout << "num_nodes: " << num_input_nodes << ", " << num_output_nodes << std::endl;
    std::vector<std::string> input_node_namestr = session.GetInputNames();
    std::vector<std::string> output_node_namestr = session.GetOutputNames();

    Ort::MemoryInfo memory_info("Cpu", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemTypeDefault);
    std::vector<float> tensor_values = { 1.0f, 2.0f, 3.0f };
    std::vector<int64_t> node_dims = { 3 };
    Ort::Value tensor = Ort::Value::CreateTensor<float>(
        memory_info,
        tensor_values.data(),
        tensor_values.size(),
        node_dims.data(),
        node_dims.size()
    );
    std::vector<Ort::Value> input_tensors;
    input_tensors.push_back(std::move(tensor));

    std::vector<const char*> input_node_names;
    std::vector<const char*> output_node_names;
    Ort::IoBinding io_binding(session);
    Ort::AllocatorWithDefaultOptions allocator;
    for (int i = 0; i < num_input_nodes; I++)
    {
        //input_node_names.push_back(input_node_namestr[i].c_str());
       Ort::AllocatedStringPtr input_name_ptr = session.GetInputNameAllocated(i, allocator);
       io_binding.BindInput(input_name_ptr.get(), input_tensors[i]);
    }
    Ort::MemoryInfo memory_info("Cuda", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemTypeDefault);
    for (int i = 0; i < num_output_nodes; I++)
    {
       // output_node_names.push_back(output_node_namestr[i].c_str());
       Ort::AllocatedStringPtr output_name_ptr = session.GetOutputNameAllocated(i, allocator);
       io_binding.BindOutput(output_name_ptr.get(), memory_info);
    }

    //std::vector<Ort::Value> output_tensors = 
    session.Run(
        Ort::RunOptions{ nullptr },
        io_binding
        /*input_node_names.data(),
        input_tensors.data(),
        num_input_nodes,
        output_node_names.data(),
        //output_tensors.data(),
        num_output_nodes*/
    );
    std::vector<Ort::Value> output_tensors = io_binding.GetOutputValues();
    std::cout << "output_tensors: " << output_tensors.size() << std::endl;
    std::cout << "memory_info device: " << output_tensors[0].GetConst().GetTensorMemoryInfo().GetDeviceType() << std::endl;

**Comment by tianleiwu** [comment]
Please take a look at API document: https://onnxruntime.ai/docs/performance/tune-performance/iobinding.html.

Here is example code generated by AI:
```
#include <iostream>
#include <vector>
#include <onnxruntime_cxx_api.h>

int main() {
    try {
        // 1. Initialize ONNX Runtime Environment
        Ort::Env env(ORT_LOGGING_LEVEL_ERROR, "demo");
        Ort::SessionOptions session_options;
        session_options.SetIntraOpNumThreads(1);
        session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_BASIC);

        // 2. Enable CUDA Execution Provider
        OrtCUDAProviderOptions options;
        options.device_id = 0;
        session_options.AppendExecutionProvider_CUDA(options);

        // 3. Create a session
        // NOTE: You'll need to replace 'xxx.onnx' with your actual model path.
        const char* model_path = "xxx.onnx";
        Ort::Session session(env, model_path, session_options);

        // 4. Get model input/output details
        Ort::AllocatorWithDefaultOptions allocator;
        size_t num_input_nodes = session.GetInputCount();
        size_t num_output_nodes = session.GetOutputCount();
        std::cout << "Number of inputs: " << num_input_nodes << ", Number of outputs: " << num_output_nodes << std::endl;

        // 5. Prepare Input Tensor on the CPU
        // The input data is first created on the CPU. ONNX Runtime will handle copying it to the GPU.
        Ort::MemoryInfo memory_info_cpu = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        std::vector<float> input_tensor_values = { 1.0f, 2.0f, 3.0f };
        std::vector<int64_t> input_node_dims = { 3 }; // Example shape

        Ort::Value input_tensor = Ort::Value::CreateTensor<float>(
            memory_info_cpu,
            input_tensor_values.data(),
            input_tensor_values.size(),
            input_node_dims.data(),
            input_node_dims.size()
        );

        // 6. Create I/O Binding
        Ort::IoBinding io_binding(session);

        // 7. Bind the input tensor
        // The input name is retrieved from the session.
        Ort::AllocatedStringPtr input_name_ptr = session.GetInputNameAllocated(0, allocator);
        io_binding.BindInput(input_name_ptr.get(), input_tensor);

        // 8. Bind the output to the GPU
        // This is the key step. We create a MemoryInfo object that points to the CUDA device.
        // By passing this to BindOutput, we instruct ONNX Runtime to place the result directly in GPU memory.
        Ort::MemoryInfo memory_info_cuda("Cuda", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemTypeDefault);
        
        for (size_t i = 0; i < num_output_nodes; ++i) {
            Ort::AllocatedStringPtr output_name_ptr = session.GetOutputNameAllocated(i, allocator);
            io_binding.BindOutput(output_name_ptr.get(), memory_info_cuda);
        }

        // 9. Run inference with the binding
        session.Run(Ort::RunOptions{ nullptr }, io_binding);

        // 10. Get the output tensor(s) from the binding
        // The output values will now be located on the GPU.
        std::vector<Ort::Value> output_tensors = io_binding.GetOutputValues();
        std::cout << "Number of output tensors: " << output_tensors.size() << std::endl;

        // 11. Verify the output tensor's location
        if (!output_tensors.empty()) {
            const Ort::TensorTypeAndShapeInfo& tensor_info = output_tensors[0].GetTensorTypeAndShapeInfo();
            const Ort::MemoryInfo& mem_info = output_tensors[0].GetTensorMemoryInfo();
            
            std::cout << "Output tensor is on device: " << mem_info.GetName() << std::endl;

            // Note: The data pointer from output_tensors[0].GetTensorData<float>() will point to GPU memory.
            // You cannot access it directly from CPU code (e.g., by printing values in a loop).
            // To access the data, you would need to copy it back to the CPU, for example using cudaMemcpy.
        }

    } catch (const Ort::Exception& e) {
        std::cerr << "ONNX Runtime error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}

```

**Comment by rscguo** [comment]
Sorry! My code has a bug.
I have fixed it and run it again and it's ok.
Thanks for your reply.
