### ISSUE TITLE
QuickGeluFusion, CUDA error cudaErrorNoKernelImageForDevice

### ISSUE THREAD

**Issue by jeffrey-cochran** [microsoft/onnxruntime#27504]
### Describe the issue

Hi y'all! 

I"m getting the following error when evaluating a session:

> Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

I'm using [pyke's Rust API](https://github.com/pykeio/ort), which is built against ONNX Runtime v1.23.2 and CUDA v12.8.

I'm using:

- NVIDIA RTX5090 (see attached image)
- NVIDIA Driver 591.74
- ONNX Runtime v1.23.2
- CUDA 12.8
- CuDNN 9.19

I've seen others with similar problems see #26241 and [here](https://github.com/kijai/ComfyUI-WanVideoWrapper/issues/1353), where some folks fixed by downgrading to v1.22.

I've also tried running against v1.24, and I get the same error.

<img width="826" height="206" alt="Image" src="https://github.com/user-attachments/assets/b1e26762-edb3-43a1-9112-2d13fbe4f3c4" />

### To reproduce

You should be able to reproduce this with a YOLOv8 model. I'll upload if you don't already have access to one, just let me know.

### Urgency

Not urgent. I will use a different execution provider until I can resolve this (DirectML works fine).

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.23.2

### ONNX Runtime API

Other / Unknown

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.8

**Comment by jeffrey-cochran** [comment]
I _think_ I figured out what was happening. 

I had a CUDA/bin folder higher on PATH discovery than the lib directory, and I think that was masking the correct dlls.

In any case, I have it working now that I removed the bin directory from PATH.
