### ISSUE TITLE
ONNXRuntime_GPU illegal memory access error

### ISSUE THREAD

**Issue by truemanlee** [microsoft/onnxruntime#2963]
Description
I encountered the illegal memory access error while using onnxruntime-gpu. But in cpu version of 
onnxruntime, the model could inference successfully.

CUDA vesrion: 10.0
CUDNN version: 7.6.5
GPU: rtx2080ti

I noticed that a similar issue occured in older version of onnxruntime, https://github.com/microsoft/onnxruntime/issues/1591. Actually, I was trying to convert the tacotron model (tensorflow implementation) into onnx format. I guessed that the error is caused by the broadcast mechanism, beacuse in dynamica decode step, it will send a "finished" signal in tf.contrib.seq2seq.Helper class.

Following is error message
 MemcpyFromHost node. Name:'Memcpy_8' Status Message:
terminate called after throwing an instance of 'onnxruntime::OnnxRuntimeException'
  what():  /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=C246-WU4 ; expr=cudaEventDestroy(read_event_);
Stacktrace:

Stacktrace:

Aborted (core dumped)

If the onnx model is needed, I would like to provide the onnx model to you

**Comment by truemanlee** [comment]
![TIM截图20200203131224](https://user-images.githubusercontent.com/10486524/73627272-ecc33700-4686-11ea-8291-bb11d8eadcaa.png)
It seems that the error is caused by the decoder part.

**Comment by hariharans29** [comment]
Can you please share the model ?

**Comment by faxu** [comment]
@truemanlee Do you still need assistance on this issue? If so, please share more details so we can help troubleshoot.

**Comment by hariharans29** [comment]
Closed. Please re-open with more info if the isue still persists.

**Comment by lee-zq** [comment]
Have you solved this problem? I have encountered the same problem. Has the problem been fixed in the latest official version？
the error info as follows:
`CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=localhost.first ; expr=cudaEventDestroy(read_event_);`
I found that the destructor of the class `cudaFence`  crashed，and it was a probabilistic event. Does anyone encounter similar bugs？

**Comment by EmreOzkose** [comment]
I had same problem. Just changed 

```
from 
Ort::MemoryInfo memory_info = Ort::MemoryInfo("Cuda:0", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);
to
auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
```

Below parameters remain same.
```
OrtCUDAProviderOptions cudaOptions;
cudaOptions.device_id = 0;
session_options.AppendExecutionProvider_CUDA(cudaOptions);
```

Then it works fine. It uses GPU and onnx model on GPU is faster x8 than CPU.

**Comment by divyansh2681** [comment]
> I had same problem. Just changed
> 
> ```
> from 
> Ort::MemoryInfo memory_info = Ort::MemoryInfo("Cuda:0", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);
> to
> auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
> ```
> 
> Below parameters remain same.
> 
> ```
> OrtCUDAProviderOptions cudaOptions;
> cudaOptions.device_id = 0;
> session_options.AppendExecutionProvider_CUDA(cudaOptions);
> ```
> 
> Then it works fine. It uses GPU and onnx model on GPU is faster x8 than CPU.

I tried this, CPU execution takes 2 seconds whereas GPU execution takes 4 seconds. This looks weird. When using GPU, input and output data needs to be moved from the CPU to the GPU right? But this code doesn't do something like this.
