### ISSUE TITLE
CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by jiushishuai88** [microsoft/onnxruntime#3117]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version:1.1.0 gpu
- Python version:3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):7.3.1
- CUDA/cuDNN version:10.0/
- GPU model and memory:

**To Reproduce**
run the sample  simple_onnxruntime_inference.ipynb
**Expected behavior**
expected run success

**Screenshots**
Fail                                      Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py in run(self, output_names, input_feed, run_options)
    140             output_names = [output.name for output in self._outputs_meta]
    141         try:
--> 142             return self._sess.run(output_names, input_feed, run_options)
    143         except C.EPFail as err:
    144             if self._enable_fallback:

Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

**Additional context**
i build from source as instrucctions ,param"./build.sh --config Release --update --build --parallel --build_wheel --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu".and install onnxruntime_gpu-1.1.0-cp36-cp36m-linux_aarch64.whl. on Jeton TX2

**Comment by jywu-msft** [comment]
What is the gpu device you are using?

**Comment by faxu** [comment]
@jiushishuai88 Do you need any more support on this?

**Comment by endeshi** [comment]
Is the problem solved?

**Comment by faxu** [comment]
Please reopen and provide more details if further assistance is needed.

**Comment by jiushishuai88** [comment]
> Please reopen and provide more details if further assistance is needed.

thks and no assiatnce is need now。The reason of that is I didn't work with the this for a long time。

**Comment by shi-yan** [comment]
I just ran into the same issue
