### ISSUE TITLE
Error loading model with ONNX Runtime with TensorRT on Jetson devices

### ISSUE THREAD

**Issue by thirdeye-callum** [microsoft/onnxruntime#3240]
Hello,

After successfully building ONNX Runtime 1.0.0 (according to https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387) on Nvidia Jetson devices (TX2, Xavier and Nano), creating an InferenceSession for a SlowFast ONNX model produces the following output:

```
Found unsupport node: 120
Found unsupport node: 132
2020-03-17 11:35:19.054683156 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:19 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-17 11:35:19.129416191 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:19 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-17 11:35:24.933445802 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:24   ERROR] ../builder/cudnnBuilderUtils.cpp (354) - Cuda Error in findFastestTactic: 4 (unspecified launch failure)
2020-03-17 11:35:24.933948237 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:35:24   ERROR] ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 4 (unspecified launch failure)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
Aborted (core dumped)
```
After increasing ORT_TENSORRT_MAX_WORKSPACE_SIZE (I have tried values ranging from 2gb to 6gb) the output becomes:
```
Found unsupport node: 120
Found unsupport node: 132
2020-03-17 11:41:59.570229117 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:41:59 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-17 11:41:59.647684879 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:41:59 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-17 11:42:01.764136091 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:42:01   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
2020-03-17 11:42:01.774280999 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-17 11:42:01   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "test_onnx.py", line 79, in <module>
    main()
  File "test_onnx.py", line 56, in main
    ort_session = ort.InferenceSession(args.model)
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 23, in __init__
    self._load_model()
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 35, in _load_model
    self._sess.load_model(self._path_or_bytes, providers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0
```
I have been able to run my model with both the CPU and CUDA Execution providers so I am assuming that where `Found unsupported node: XXX` appears ONNX Runtime should successfully fallback to a non-TensorRT provider.

It seems strange that the TX2 and Xavier would be running out of GPU memory given that the model normally only requires ~1.5gb GPU memory when running in PyTorch.

## System information
- NVIDIA Jetson TX2, Xavier, Nano flashed with JetPack 4.3
- OS Platform and Distribution: L4T 32.3.1
- ONNX Runtime installed from source
- ONNX Runtime version 1.0.0 https://github.com/microsoft/onnxruntime/commit/b783805f957c88f97b2b4398e2ace138fbdf831b
- Python version: Python 3.6.9
- GCC/Compiler version: 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: 10.0.326/7.6.3
- GPU model and memory:  
  - Nvidia Jetson TX2 - 8gb shared between CPU and GPU
  - Nvidia Jetson Xavier - 32gb shared between CPU and GPU
  - Nvidia Jetson Nano - 4gb shared between CPU and GPU

### ONNX Runtime Installation
- Flash Jetson device with Jetpack 4.3
- Upgrade cmake to version 3.13.5 (following https://anglehit.com/how-to-install-the-latest-version-of-cmake-via-command-line/)
- `sudo apt-get install python3-dev python3-pip`
- `pip3 install cython numpy`
- build using specified instructions https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387
- `pip3 install ./build/Linux/Release/dist/onnxruntime_gpu_tensorrt-1.0.0-cp36-cp36m-linux_aarch64.whl`

### Run Instructions
- Download model from https://drive.google.com/file/d/1d6eZkPcWam4CfCFERlbFJHtJ0ZLoAqmm/view?usp=sharing
- Run following python script ensuring that `model_path` is correct:
```
import numpy as np
import onnxruntime as ort

model_path = 'model_export_20200316_175122_class.onnx'

ort_session = ort.InferenceSession(model_path)
feed_dict = {}
feed_dict['slow'] = np.random.randn(1, 3, 8, 256, 256).astype(np.float32)
feed_dict['fast'] = np.random.randn(1, 3, 32, 256, 256).astype(np.float32)
print('Running inference...')
outputs = ort_session.run(
    None,
    feed_dict
)
print('Success!')
print(outputs)
```

## Expected behavior
As above, `Cuda Error in free` initially. Once TensorRT's maximum workspace is increased `Cuda Error in allocate`

## Additional context
- I am able to load ResNet18 and ResNet152 from the ONNX Model Zoo with the Tensorrt Execution Provider
- I am able to load my Model using both CPU and CUDA Execution Providers
- Re-exporting my model with with opset 7 produces the same errors

**Comment by thirdeye-callum** [comment]
Worked out I could actually use a more recent ONNX Runtime commit (I had assumed the one mentioned https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387 was the most recent commit with the correct CUDA/cuDNN/TensorRT versions). After building ONNX Runtime 1.1.0 (https://github.com/microsoft/onnxruntime/commit/273868eaa55431164a2e5b5a94b8941bd550a7c3) I no longer see any `Found unsupport node: XXX` messages, but otherwise the error is the same:
```
2020-03-18 20:08:48.705396756 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-18 20:08:48 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-18 20:08:48.900676539 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-18 20:08:48 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-18 20:08:50.657570787 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-18 20:08:50   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
2020-03-18 20:08:50.667367447 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-18 20:08:50   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "test_onnx.py", line 87, in <module>
    main()
  File "test_onnx.py", line 61, in main
    ort_session = ort.InferenceSession(args.model, providers=['TensorrtExecutionProvider','CUDAExecutionProvider','CPUExecutionProvider'])
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0
```

**Comment by thirdeye-callum** [comment]
Above I mentioned that I get `Cuda Error in free` when ORT_TENSORRT_MAX_WORKSPACE is too small but it also seems to happen when it is too big.

When I set ORT_TENSORRT_MAX_WORKSPACE=2147483648 on the Jetson TX2 i run into `Cuda Error in allocate: 2 (out of memory)`, my tegrastats output is as follows:
```
RAM 309/7852MB (lfb 1810x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,0%@345,3%@345,1%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.4C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/768 VDD_4V0_WIFI 0/0 VDD_IN 3024/3028 VDD_SYS_CPU 153/156 VDD_SYS_DDR 537/538
RAM 310/7852MB (lfb 1810x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40C MCPU@40C PMIC@100C Tboard@37C GPU@38.5C BCPU@40C thermal@39.6C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/767 VDD_4V0_WIFI 0/0 VDD_IN 3024/3028 VDD_SYS_CPU 153/155 VDD_SYS_DDR 537/538
RAM 309/7852MB (lfb 1810x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40C MCPU@40C PMIC@100C Tboard@37C GPU@38.5C BCPU@40C thermal@39.4C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/767 VDD_4V0_WIFI 0/0 VDD_IN 3024/3028 VDD_SYS_CPU 153/155 VDD_SYS_DDR 537/538
RAM 325/7852MB (lfb 1797x4MB) SWAP 0/3926MB (cached 0MB) CPU [40%@652,off,off,3%@652,1%@652,0%@652] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.7C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 841/770 VDD_4V0_WIFI 0/0 VDD_IN 3942/3060 VDD_SYS_CPU 535/169 VDD_SYS_DDR 768/546
RAM 508/7852MB (lfb 1696x4MB) SWAP 0/3926MB (cached 0MB) CPU [23%@1961,off,off,28%@2035,7%@2036,8%@2034] EMC_FREQ 2%@1600 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.9C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/775 VDD_4V0_WIFI 0/0 VDD_IN 4324/3104 VDD_SYS_CPU 535/181 VDD_SYS_DDR 902/558
RAM 663/7852MB (lfb 1634x4MB) SWAP 0/3926MB (cached 0MB) CPU [33%@1537,off,off,9%@1727,5%@1728,6%@1727] EMC_FREQ 2%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/780 VDD_4V0_WIFI 0/0 VDD_IN 4248/3142 VDD_SYS_CPU 535/193 VDD_SYS_DDR 902/570
RAM 1032/7852MB (lfb 1527x4MB) SWAP 0/3926MB (cached 0MB) CPU [77%@2036,off,off,2%@2035,0%@2036,0%@2036] EMC_FREQ 5%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 994/787 VDD_4V0_WIFI 0/0 VDD_IN 4782/3195 VDD_SYS_CPU 917/217 VDD_SYS_DDR 1152/589
RAM 2357/7852MB (lfb 1196x4MB) SWAP 0/3926MB (cached 0MB) CPU [100%@2035,off,off,0%@2035,0%@2037,0%@2036] EMC_FREQ 9%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 994/793 VDD_4V0_WIFI 0/0 VDD_IN 5049/3253 VDD_SYS_CPU 994/241 VDD_SYS_DDR 1324/612
RAM 2358/7852MB (lfb 1185x4MB) SWAP 0/3926MB (cached 0MB) CPU [90%@959,off,off,0%@960,0%@959,0%@960] EMC_FREQ 13%@1331 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 994/799 VDD_4V0_WIFI 0/0 VDD_IN 4820/3300 VDD_SYS_CPU 841/259 VDD_SYS_DDR 1171/629
RAM 2389/7852MB (lfb 1148x4MB) SWAP 0/3926MB (cached 0MB) CPU [55%@1728,off,off,1%@1728,0%@1728,0%@1729] EMC_FREQ 6%@1600 GR3D_FREQ 2%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.75C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/803 VDD_4V0_WIFI 0/0 VDD_IN 4324/3330 VDD_SYS_CPU 611/269 VDD_SYS_DDR 902/637
RAM 2448/7852MB (lfb 1103x4MB) SWAP 0/3926MB (cached 0MB) CPU [44%@1970,off,off,14%@2035,0%@2035,1%@2035] EMC_FREQ 5%@1600 GR3D_FREQ 1%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/806 VDD_4V0_WIFI 0/0 VDD_IN 4363/3360 VDD_SYS_CPU 611/279 VDD_SYS_DDR 921/645
RAM 2508/7852MB (lfb 1059x4MB) SWAP 0/3926MB (cached 0MB) CPU [57%@2034,off,off,3%@2035,0%@2035,0%@2035] EMC_FREQ 4%@1600 GR3D_FREQ 8%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/809 VDD_4V0_WIFI 0/0 VDD_IN 4324/3387 VDD_SYS_CPU 611/288 VDD_SYS_DDR 921/652
RAM 1492/7852MB (lfb 1237x4MB) SWAP 0/3926MB (cached 0MB) CPU [56%@2033,off,off,21%@2032,5%@2033,0%@2033] EMC_FREQ 4%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/812 VDD_4V0_WIFI 0/0 VDD_IN 4286/3411 VDD_SYS_CPU 764/301 VDD_SYS_DDR 902/659
RAM 635/7852MB (lfb 1440x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,8%@345,12%@345,0%@345] EMC_FREQ 3%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@39C BCPU@40.5C thermal@39.9C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 841/813 VDD_4V0_WIFI 0/0 VDD_IN 3214/3406 VDD_SYS_CPU 306/301 VDD_SYS_DDR 595/657
RAM 636/7852MB (lfb 1440x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 3%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@39C BCPU@40.5C thermal@39.9C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/812 VDD_4V0_WIFI 0/0 VDD_IN 3024/3396 VDD_SYS_CPU 153/297 VDD_SYS_DDR 537/654
RAM 635/7852MB (lfb 1440x4MB) SWAP 0/3926MB (cached 0MB) CPU [0%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 3%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@39C BCPU@40.5C thermal@39.9C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/810 VDD_4V0_WIFI 0/0 VDD_IN 3024/3387 VDD_SYS_CPU 153/294 VDD_SYS_DDR 537/651
RAM 635/7852MB (lfb 1440x4MB) SWAP 0/3926MB (cached 0MB) CPU [0%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@39C BCPU@40.5C thermal@39.9C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/809 VDD_4V0_WIFI 0/0 VDD_IN 3024/3378 VDD_SYS_CPU 153/290 VDD_SYS_DDR 537/649
RAM 635/7852MB (lfb 1440x4MB) SWAP 0/3926MB (cached 0MB) CPU [0%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.9C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/808 VDD_4V0_WIFI 0/0 VDD_IN 3024/3369 VDD_SYS_CPU 153/287 VDD_SYS_DDR 537/646
RAM 635/7852MB (lfb 1440x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.7C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/807 VDD_4V0_WIFI 0/0 VDD_IN 3024/3361 VDD_SYS_CPU 153/284 VDD_SYS_DDR 537/643
```
When I set ORT_TENSORRT_MAX_WORKSPACE=4294967296 on the Jetson TX2 i run into `Cuda Error in free: 4 (unspecified launch failure)`, my tegrastats output is as follows:
```
RAM 311/7852MB (lfb 1809x4MB) SWAP 0/3926MB (cached 0MB) CPU [0%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1331 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.7C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 765/765 VDD_4V0_WIFI 0/0 VDD_IN 3024/3024 VDD_SYS_CPU 153/153 VDD_SYS_DDR 537/537
RAM 328/7852MB (lfb 1792x4MB) SWAP 0/3926MB (cached 0MB) CPU [44%@1428,off,off,1%@1585,2%@1573,4%@1574] EMC_FREQ 1%@1600 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.7C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 841/777 VDD_4V0_WIFI 0/0 VDD_IN 4095/3202 VDD_SYS_CPU 535/216 VDD_SYS_DDR 806/581
RAM 518/7852MB (lfb 1695x4MB) SWAP 0/3926MB (cached 0MB) CPU [41%@960,off,off,9%@499,2%@499,3%@498] EMC_FREQ 3%@1600 GR3D_FREQ 0%@114 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@40.5C thermal@39.7C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/797 VDD_4V0_WIFI 0/0 VDD_IN 4363/3368 VDD_SYS_CPU 535/262 VDD_SYS_DDR 940/633
RAM 708/7852MB (lfb 1617x4MB) SWAP 0/3926MB (cached 0MB) CPU [42%@2036,off,off,5%@2035,2%@2036,9%@2034] EMC_FREQ 3%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@38.5C BCPU@41C thermal@39.7C Tdiode@38.25C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/812 VDD_4V0_WIFI 0/0 VDD_IN 4286/3483 VDD_SYS_CPU 611/305 VDD_SYS_DDR 902/666
RAM 1233/7852MB (lfb 1476x4MB) SWAP 0/3926MB (cached 0MB) CPU [85%@2034,off,off,1%@2035,0%@2035,0%@2035] EMC_FREQ 6%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@38.5C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 994/832 VDD_4V0_WIFI 0/0 VDD_IN 4858/3635 VDD_SYS_CPU 917/373 VDD_SYS_DDR 1190/724
RAM 2394/7852MB (lfb 1186x4MB) SWAP 0/3926MB (cached 0MB) CPU [100%@2036,off,off,0%@2036,0%@2037,0%@2035] EMC_FREQ 10%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.3C Tdiode@38.75C VDD_SYS_GPU 229/229 VDD_SYS_SOC 994/849 VDD_4V0_WIFI 0/0 VDD_IN 5126/3784 VDD_SYS_CPU 1070/443 VDD_SYS_DDR 1344/786
RAM 2363/7852MB (lfb 1188x4MB) SWAP 0/3926MB (cached 0MB) CPU [75%@2028,off,off,19%@2031,0%@2032,0%@2033] EMC_FREQ 10%@1600 GR3D_FREQ 0%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.5C Tdiode@38.75C VDD_SYS_GPU 229/229 VDD_SYS_SOC 917/855 VDD_4V0_WIFI 0/0 VDD_IN 4667/3865 VDD_SYS_CPU 917/486 VDD_SYS_DDR 1094/814
RAM 2400/7852MB (lfb 1141x4MB) SWAP 0/3926MB (cached 0MB) CPU [46%@1966,off,off,4%@2034,1%@2034,0%@2034] EMC_FREQ 7%@1600 GR3D_FREQ 28%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/860 VDD_4V0_WIFI 0/0 VDD_IN 4324/3903 VDD_SYS_CPU 611/496 VDD_SYS_DDR 921/823
RAM 2452/7852MB (lfb 1098x4MB) SWAP 0/3926MB (cached 0MB) CPU [56%@2034,off,off,1%@2035,1%@2035,0%@2035] EMC_FREQ 5%@1600 GR3D_FREQ 4%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40C Tdiode@38.75C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/864 VDD_4V0_WIFI 0/0 VDD_IN 4363/3938 VDD_SYS_CPU 611/505 VDD_SYS_DDR 921/831
RAM 2511/7852MB (lfb 1056x4MB) SWAP 0/3926MB (cached 0MB) CPU [34%@1514,off,off,17%@1513,1%@1515,9%@1512] EMC_FREQ 4%@1600 GR3D_FREQ 9%@114 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.5C VDD_SYS_GPU 229/229 VDD_SYS_SOC 918/868 VDD_4V0_WIFI 0/0 VDD_IN 4248/3960 VDD_SYS_CPU 535/507 VDD_SYS_DDR 902/836
RAM 2621/7852MB (lfb 1020x4MB) SWAP 0/3926MB (cached 0MB) CPU [28%@345,off,off,0%@345,5%@345,11%@345] EMC_FREQ 5%@1600 GR3D_FREQ 94%@930 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@41C BCPU@41C thermal@40.2C Tdiode@39.5C VDD_SYS_GPU 1834/336 VDD_SYS_SOC 917/871 VDD_4V0_WIFI 0/0 VDD_IN 5623/4071 VDD_SYS_CPU 382/499 VDD_SYS_DDR 1017/848
RAM 2653/7852MB (lfb 1012x4MB) SWAP 0/3926MB (cached 0MB) CPU [5%@1804,off,off,1%@2034,13%@2029,31%@2034] EMC_FREQ 13%@1600 GR3D_FREQ 99%@1134 APE 150 PLL@41.5C MCPU@41.5C PMIC@100C Tboard@37C GPU@40.5C BCPU@41.5C thermal@41.4C Tdiode@41.75C VDD_SYS_GPU 3437/529 VDD_SYS_SOC 993/879 VDD_4V0_WIFI 0/0 VDD_IN 7418/4280 VDD_SYS_CPU 458/496 VDD_SYS_DDR 1344/879
RAM 710/7852MB (lfb 1439x4MB) SWAP 0/3926MB (cached 0MB) CPU [37%@499,off,off,7%@498,12%@499,22%@498] EMC_FREQ 7%@1600 GR3D_FREQ 0%@1134 APE 150 PLL@41.5C MCPU@41.5C PMIC@100C Tboard@37C GPU@39.5C BCPU@41.5C thermal@41C Tdiode@39.25C VDD_SYS_GPU 382/521 VDD_SYS_SOC 918/881 VDD_4V0_WIFI 0/0 VDD_IN 4248/4278 VDD_SYS_CPU 611/503 VDD_SYS_DDR 921/881
RAM 710/7852MB (lfb 1439x4MB) SWAP 0/3926MB (cached 0MB) CPU [2%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 4%@1600 GR3D_FREQ 0%@1134 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.75C VDD_SYS_GPU 229/504 VDD_SYS_SOC 841/879 VDD_4V0_WIFI 0/0 VDD_IN 3444/4232 VDD_SYS_CPU 229/488 VDD_SYS_DDR 806/877
RAM 710/7852MB (lfb 1439x4MB) SWAP 0/3926MB (cached 0MB) CPU [0%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 3%@1600 GR3D_FREQ 0%@1134 APE 150 PLL@41C MCPU@41C PMIC@100C Tboard@37C GPU@39C BCPU@41C thermal@40.2C Tdiode@38.75C VDD_SYS_GPU 153/486 VDD_SYS_SOC 841/877 VDD_4V0_WIFI 0/0 VDD_IN 3367/4186 VDD_SYS_CPU 153/470 VDD_SYS_DDR 787/872
RAM 710/7852MB (lfb 1439x4MB) SWAP 0/3926MB (cached 0MB) CPU [1%@345,off,off,0%@345,0%@345,0%@345] EMC_FREQ 2%@1600 GR3D_FREQ 0%@1134 APE 150 PLL@40.5C MCPU@40.5C PMIC@100C Tboard@37C GPU@39C BCPU@40.5C thermal@40.2C Tdiode@38.75C VDD_SYS_GPU 153/469 VDD_SYS_SOC 841/875 VDD_4V0_WIFI 0/0 VDD_IN 3367/4145 VDD_SYS_CPU 153/454 VDD_SYS_DDR 787/868
```
Neither of the tegrastats outputs suggest particularly high memory usage althouhg I guess its quite possible that it is missing the peaks.

**Comment by thirdeye-callum** [comment]
I have been playing with the ORT_TENSORRT_MAX_PARTITION_ITERATIONS value. My understanding is that every time TensorRT doesn't support an operation the graph will be partitioned, so that the unsupported node(s) is run using a fallback provider (CUDA or CPU). If we have to partitions more than ORT_TENSORRT_MAX_PARTITION_ITERATIONS then the whole graph falls back to the fallback provider.

- With a value of 1 I get no warnings and the graph falls back to another provider and runs successfully.
- With a value of 2 I get the following warning and the graph falls back to another provider and runs successfully:
```
2020-03-19 09:03:50.109044117 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:03:50 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
```
- With a value of 3 I get the following warnings and the same error again:
```
2020-03-19 09:04:25.529049981 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:25 WARNING] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-03-19 09:04:25.721145280 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:25 WARNING] Setting layouts of network and plugin input/output tensors to linear, as 3D operators are found and 3D non-linear IO formats are not supported, yet.
2020-03-19 09:04:27.483482298 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:27   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
2020-03-19 09:04:27.490360049 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2020-03-19 09:04:27   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "test_onnx.py", line 87, in <module>
    main()
  File "test_onnx.py", line 61, in main
    ort_session = ort.InferenceSession(args.model, providers=['TensorrtExecutionProvider','CUDAExecutionProvider','CPUExecutionProvider'])
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/home/callum/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0
```
Maybe this suggests:
-  that the 2nd or 3rd (I am not sure if the max value is inclusive) subgraph (or the optimization of that subgraph) requires too much memory 
- or that the act of building multiple TensorRT subgraphs requires too much memory

**Comment by thirdeye-dimitris** [comment]
Note that ONNX Runtime 1.0.0 b783805 has been built on desktop and the TensorRT provider successfully launched on GeForce GTX 1080 Ti.

NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1

**Comment by ZhengtianXu** [comment]
I also met this problem in my PC, with onnxruntime-gpu==1.1.0 and tensorrt 6.0. When I load two models, one with onnx and the other with trt, it causes the following errors.
```
[TensorRT] ERROR: ../rtSafe/cuda/cudaElementWiseRunner.cpp (149) - Cuda Error in execute: 33 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
```

Can onnxruntime run with tensorrt together?

**Comment by Darshcg** [comment]
Hi @thirdeye-callum,

Can you please assist me in converting the Slow Fast Pytorch model into ONNX model?
Would be a great help from your side.
