### ISSUE TITLE
onxruntime-gpu installation issues

### ISSUE THREAD

**Issue by sayak1711** [microsoft/onnxruntime#5020]
**Describe the bug**
I can't import onnxruntime succesfully after installing onnxruntime-gpu
`OSError: libcublas.so.10: cannot open shared object file: No such file or directory`

**System information**
- OS Platform and Distribution : Ubuntu 18.04.4
- ONNX Runtime installed from (source or binary): pip install onnxruntime-gpu
- ONNX Runtime version: onnxruntime-gpu-1.4.0
- Python version: 3.6.9
- CUDA/cuDNN version: CUDA: 10.1 cuDNN: 7.6.5
- GPU model and memory: NVIDIA Tesla K80

**To Reproduce**
Remove existing CUDA
Then install the CUDA and cuDNN as per steps given in NVIDIA website
CUDA installation: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
cuDNN installation: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html
Then pip install onnxruntime-gpu
import onnxruntime

**Expected behavior**
onnxruntime gets imported without error

.

**Comment by jywu-msft** [comment]
is your LD_LIBRARY_PATH set properly so the cuda libs can be found?
https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html#post-installation-actions

**Comment by sayak1711** [comment]
Yes I had added those in my bashrc as well. Still it gives same error upon reinstalling onnxruntime-gpu

I finally was able to fix it by using a hack.

I noticed that the file it couldn't find were present in cuda-10.2 folder.

`sudo cp /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcublas.so.10 /usr/local/cuda-10.1/lib64/
sudo cp /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcublasLt.so.10 /usr/local/cuda-10.1/lib64/
`
Then I could import onnx

`
>>> import onnxruntime
>>> onnxruntime.get_device()
'GPU'
>>> exit()
`

**Comment by jywu-msft** [comment]
if i'm understanding correctly,
you previously installed both cuda 10.1 and 10.2 on your system?  but the cuda 10.1 installation dir was missing the shared libs?

**Comment by sayak1711** [comment]
Correct

**Comment by snnn** [comment]
Nvidia suddenly removed the cublas for CUDA 10.1.  You installed cublas 10.2 .

**Comment by pranavsharma** [comment]
I used [this image](https://hub.docker.com/layers/nvidia/cuda/10.1-cudnn7-runtime-ubuntu16.04/images/sha256-66e68a811e326335c16401c4c551b37847b525a04ebf667f8473794f3e42ed6c?context=explore) and installed ORT in it and didn't find any issue. I don't have a 18.04 handy to try there.

root@221c18c41b09:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

root@221c18c41b09:/# pip list | grep onnxruntime
onnxruntime-gpu     1.4.0
You are using pip version 19.0.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

root@221c18c41b09:/# python3 -c 'import onnxruntime as rt; print(rt.get_device())'
GPU
root@221c18c41b09:/#

**Comment by pranavsharma** [comment]
After running apt-get update && apt-get upgrade, this stops working.

root@221c18c41b09:/# python3 -c 'import onnxruntime as rt; print(rt.get_device())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/_pybind_state.py", line 9, in <module>
    import onnxruntime.capi._ld_preload  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcublas = CDLL("libcublas.so.10", mode=RTLD_GLOBAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.10: cannot open shared object file: No such file or directory
root@221c18c41b09:/#

**Comment by Exlsunshine** [comment]
Do we have any solution to this `OSError: libcublas.so.10` issue?

**Comment by sayak1711** [comment]
Hi @Exlsunshine Right now the solution would be to copy libcublas.so.10 and libcublasLt.so.10 from CUDA 10.2 like I mentioned.

**Comment by jywu-msft** [comment]
the issue here is with doing any system upgrades which upgrades your libcublas10 version.
libcublas10 version 10.2.1.243-1 gets installed in /usr/local/cuda-10.1/lib64
if you update to version 10.2.2.214-1 it gets installed in /usr/local/cuda-10.2/lib64 , even if you never installed cuda 10.2
that is why onnxruntime cannot find the library (and @sayak1711's workaround of copying the libs to cuda-10.1 directory works)
per nvidia's guidance, another way is to hold libcublas10 to the old version using `apt-mark hold libcublas10` to prevent system upgrades from upgrading it.

**Comment by Exlsunshine** [comment]
> h

Thanks for the details, copying `.so` is no big deal, but do we have to do this manually all the time or just temporary?

**Comment by Exlsunshine** [comment]
> the issue here is with doing any system upgrades which upgrades your libcublas10 version.
> libcublas10 version 10.2.1.243-1 gets installed in /usr/local/cuda-10.1/lib64
> if you update to version 10.2.2.214-1 it gets installed in /usr/local/cuda-10.2/lib64 , even if you never installed cuda 10.2
> that is why onnxruntime cannot find the library (and @sayak1711's workaround of copying the libs to cuda-10.1 directory works)
> per nvidia's guidance, another way is to hold libcublas10 to the old version using `apt-mark hold libcublas10` to prevent system upgrades from upgrading it.

Thanks for the details, copying `.so` is no big deal, but do we have to do this manually all the time or just temporary?

**Comment by becks-ddf** [comment]
Trying to install onnxruntime-gpu into docker container nvcr.io/nvidia/tensorrt:20.09-py3 and have the same problem when importing onnxruntime.
`OSError: libcublas.so.10: cannot open shared object file: No such file or directory`

**Comment by AbhijitManepatil** [comment]
Check for Cuda and cuDNN version
refer [https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html] for version understanding.
example: if you have Cuda 10.2 then you require cuDNN 8.0.3




> Trying to install onnxruntime-gpu into docker container nvcr.io/nvidia/tensorrt:20.09-py3 and have the same problem when importing onnxruntime.
> `OSError: libcublas.so.10: cannot open shared object file: No such file or directory`

**Comment by v-nhandt21** [comment]
Thank god I got the solution, 
![WeeklyReport_TTS](https://user-images.githubusercontent.com/36092323/126825712-a3e42a50-d2c1-4b80-af09-adfbe34236c3.png)

For whom work with docker deployment
```
FROM nvidia/cuda:10.2-cudnn8-runtime-ubuntu18.04

COPY . /

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
RUN apt-get -y install python3.7
RUN apt-get -y install python3-pip
```
