### ISSUE TITLE
cudaErrorInvalidConfiguration in FusedBatchNormV3

### ISSUE THREAD

**Issue by bdnkth** [microsoft/onnxruntime#7316]
**Describe the bug**
I have custom trained the EfficientDetD0 model from the TensorFlow model zoo for object detection and exported the model to onnx with tf2onnx using opset 11 and fixed input of [1,512,512,3].
Using that onnx model in the onnx runtime for C++ I run into a cudaErrorInvalidConfiguration in FusedBatchNormV3_528 of the EfficientDet.
Full errr message is:
2021-04-12 14:58:25.6606830 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Transpose node. Name:'StatefulPartitionedCall/EfficientDet-D0/bifpn/node_03/1_dn_lvl_5/input_0_up_lvl_5/1x1_pre_sample/batchnorm/FusedBatchNormV3__528' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

Our old onnx models which were made in TF 1.15 are running without an error through the code. TF 2.4.0 models do not.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary):  binary
- ONNX Runtime version: 1.7.0
- Python version: 2.4.1
- Visual Studio version (if applicable): 16.9.3
- GCC/Compiler version (if compiling from source):  v142
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 3090 24gb

**To Reproduce**
- The EfficientDetD0 onnx model is attached: [model.zip](https://github.com/microsoft/onnxruntime/files/6297337/model.zip)

**Expected behavior**
There should be no cudaErrorInvalidConfiguration

**Comment by hariharans29** [comment]
I didn't find a transpose that ended with __528. Instead I found one ending with __527 so I am assuming that is the one. 

It seems like the Transpose works with 5D tensors and so I am guessing it enters the non-cublas/non-3d/non-4d implementation of ours (the "generic" path - https://github.com/microsoft/onnxruntime/blob/21c282ed542e7673d1eea0f54e113b84c40d5c50/onnxruntime/core/providers/cuda/tensor/transpose.cc#L179). I wonder if it is triggering something here.

**Comment by hariharans29** [comment]
Btw - can you run the model with just cpu and check if the results are okay - that will rule out any model issues and to prioritize accordingly - is there a timeline you are looking at to have these resolved ?

**Comment by bdnkth** [comment]
Hi,
thank you for the fast reply. Indeed, it is __527, I mixed something with the __528 which comes from a different input layer which I did some experiments with to exclude the input size as the root of this problem.

The model runs on the CPU without an error, only the CUDA execution fails with the cudaErrorInvalidConfiguration.
Regarding the timeline: At the moment the CPU version is sufficient to test our pipeline. However, runtime is crucial for us, so we have to use to CUDA version as CPU execution time is too high. We have to make runtime benchmarks in the near future to see if our pipeline and our models stay below our maximum execution time. So it's not super urgent for our immediate timeline, but important for the near future.

**Comment by hariharans29** [comment]
I figured out the issue - it triggers a corner case bug in our Transpose CUDA implementation.

I ll need to think about the fix and I ll send it out shortly.

**Comment by hariharans29** [comment]
Can you build from source and make sure the bug fix works with all your models

**Comment by bdnkth** [comment]
We have tested the bug fix and it works with our previously failing models. They run perfectly and produce the expected results. Thank you very much for providing a fix in such a short timeframe.
Just one question: Do you have an approximate date, when this fix could be included in a official release? It is totally fine for us to use the self-compiled version of onnx to test our models and code, but haing an official binary release would be benefitful for our development pipeline.

**Comment by hariharans29** [comment]
Thanks for taking the time to verify the change. 

It could be that my fix has a bug - I ll get back to you on this.

**Comment by bdnkth** [comment]
Could this be caused by the NonMaxSuppression? The net should only detect one bounding box per image (there is only one object per image in our dataset at the moment). Since the net detects multiple objects when running on the GPU we have the guess, that this might be the problem.

Unfortunately I wanted to do some experiments with a different self trained object detection model from Tensorflow's model zoo but I ran into a bug in tf2onnx.

**Comment by bdnkth** [comment]
Do you have any updates regarding this problem? Or are there additional information you need from me?

**Comment by hariharans29** [comment]
Thanks for the reminder. I think I have all that I need from you. I need to refine my change a bit but I have been busy with some high priority work-items recently. I will make sure a fix makes it into our next release.

**Comment by hariharans29** [comment]
Hi @bdnkth  - Can you try re-building the fix branch and testing your models again ? Thanks.

**Comment by bdnkth** [comment]
The EfficientDet runs now as expected on the GPU. I get the same results as with the CPU execution and execution time is fine. I had some initial build problems with your code yesterday, which are now fixed. Maybe my build pipeline screwed something up or your last fix commit solved that problem.
Thank you for providing a working fix for the problem.

**Comment by hariharans29** [comment]
Thanks for testing the fix.

**Comment by zx-lhb** [comment]
hi, i met the same problem when use onnx model converted by tf2onn to do inference, how can i fix it, can you help me?
```python
2023-05-18 14:21:33.2750436 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Transpose node. Name:'StatefulPartitionedCall/attnGateVnet3d/conv3d_48/Conv3D__890' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

```
