### ISSUE TITLE
CUDNN failure 3: CUDNN_STATUS_BAD_PARAM for FusedConv node at inference time

### ISSUE THREAD

**Issue by piraka9011** [microsoft/onnxruntime#8024]
**Describe the bug**

I'm trying to run a CNN based model that runs fine on CPU but fails on GPU/Cuda with the following error:

```
2021-06-10 19:07:40.032075878 [E:onnxruntime:Default, cuda_call.cc:117 CudaCall] CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=b85281d3196e ; expr=cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data); 
2021-06-10 19:07:40.032103059 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running FusedConv node. Name:'Conv_17_Add_18_Relu_19' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)
Traceback (most recent call last):
  File "benchmark.py", line 118, in <module>
    main()
  File "benchmark.py", line 98, in main
    logits = sess.run([output_name], inputs)
  File "/home/allabana/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'Conv_17_Add_18_Relu_19' Status Message: CUDNN error executing cudnnAddTensor(Base::CudnnHandle(), &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data)

```
I tried the following `onnxruntime-gpu` versions on the same system info below:
* 1.8.0 from pip
* 1.8.0 from source

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker Ubuntu 18.04
- ONNX Runtime installed from (source or binary): See above
- ONNX Runtime version: See above
- Python version: 3.8.8
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 11.1.105 / 8.0.5
- GPU model and memory: RTX3090 

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```py
import torch
import onnxruntime

sess = onnxruntime.InferenceSession(onnx_model_path)
input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name
processed_signal = torch.randn((1, 64, 2458))
inputs = {input_name: processed_signal}
logits = sess.run([output_name], inputs)  # Fails here
```

- Attach the ONNX model to the issue (where applicable) to expedite investigation.

Not sure how to post one here...

**Expected behavior**

Inference works

Update: I compiled v1.5.1 from source with this command and inference works. Seems to be a problem with v1.5.1+

```sh
./build.sh --skip_tests --config Release --build_shared_lib --parallel --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu --build_wheel
```

**Comment by hariharans29** [comment]
CC: @RandyShuai - I think he added the supported Conv activation fusion on CUDA (which was added post 1.5.1).

To unblock yourself, you could disable optimizations and I think it should run albeit a bit slower given that graph optimizations have been disabled.

**Comment by piraka9011** [comment]
>To unblock yourself, you could disable optimizations

To clarify, you mean cuda optimizations? (`sess.set_providers(['CPUExecutionProvider'])`
Or graph optimization? (`sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL`)

**Comment by piraka9011** [comment]
I can confirm that this works on 1.8.0 with `CUDAExecutionProvider` only if `graph_optimization_level` is `ORT_ENABLE_BASIC` or `ORT_DISABLE_ALL`.
I am currently sticking to CPU because it is faster than CUDA (Looks like CUDA isn't being used at all...)
Inference time takes 0.2369s on `CPUExecutionProvider` vs 1.6815s `CUDAExecutionProvider`.

**Comment by hariharans29** [comment]
Sorry I meant this: sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL

The reason why it works on CUDA with ORT_DISABLE_ALL and ORT_ENABLE_BASIC is that this specific optimizer belongs to "Extended" class of optimizers and it will get triggered only if ORT_ENABLE_EXTENDED or higher is turned on. 

If the model is shareable, we could investigate the cause of the failure within the optimizer (CC: @RandySheriffH ).

For the CUDA perf concern, we could do some preliminary investigation with the model. On a related note, is your model a dynamic shape model or are the input shapes fixed ? Are you performing warm-up runs prior to measuring perf ?

**Comment by piraka9011** [comment]
Input shapes: `['signal_dynamic_axes_1', 64, 'signal_dynamic_axes_2']` BatchNum x Features x SequenceLength
Output shapes: `['logprobs_dynamic_axes_1', 'logprobs_dynamic_axes_2', 38]` BatchNum x SequenceLength x Labels
No warm-up runs, just a single run measured using Python's `time` library. (I'm not familiar with warm-up runs though, is that documented anywhere/common practice?)

**Comment by piraka9011** [comment]
FWIW, I built an image using TensorRT for v.1.8.0 and the performance is even worse (~20s for inference).
The model is based off of NeMo's [Quartznet](https://github.com/NVIDIA/NeMo/blob/df05895bcf4e8335f1738252383fac7f7e0a3ea2/nemo/collections/asr/models/ctc_models.py#L40) (The primary building block is [here](https://github.com/NVIDIA/NeMo/blob/df05895bcf4e8335f1738252383fac7f7e0a3ea2/nemo/collections/asr/parts/submodules/jasper.py#L489)).

You can use [this script](https://github.com/NVIDIA/NeMo/blob/df05895bcf4e8335f1738252383fac7f7e0a3ea2/scripts/export/convasr_to_single_onnx.py) to get an onnx model from one of their `.nemo` models:

**Comment by hariharans29** [comment]
`I'm not familiar with warm-up runs though, is that documented anywhere/common practice?`

Usually it is common practice to run a few warm-up runs (atleast one run) before measuring perf. The very first run usually caches some information for subsequent runs. Please at-least do one run before you measure perf. It may improve the perf numbers.

Dynamic shape models do suffer from a further limitation: the first time it sees a new shape, it needs to re-compute some information in certain nodes and this may lead to increased latency. 

It may be worth noting that In this case, the perf drop may also be due to the fact that we are disabling graph optimizations (to circumvent the fused conv issue you hit).

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
