### ISSUE TITLE
[Windows+Java+Onnxruntime] GPU Util is low and inferrencing speed is slow

### ISSUE THREAD

**Issue by MianMianMeow** [microsoft/onnxruntime#8167]
Hi,
  I'm using Java Onnxruntime on Windows 10 for model inference,  but from _nvidia-smi_ the GPU-Util is about only 15% and inferencing speed by setting execution provider as CUDA is around 350 ms/frame. However, the inferencing speed by setting execution provider as CPU is around 450 ms/frame, which seems there is no much acceleration by GPU for inference. Moreover,  I also tried to use the same model.onnx for inferencing on Ubuntu+Python+onnxruntime and in this case the GPU-Util is about 70% which seems good. I haven't check the inferencing speed per frame in this case but the speed seems much faster while doing the inference on a video frames.
  Since I'm not sure if this problem is related to Java Onnxrumtime API or OS, Maybe I should do the experiment on Windows+Python+Onnxruntime to figure out the problem?
  

**Urgency**
none

**System information**
- Windows 10
- ONNX Runtime installed from binary(?): installed onnxruntime_gpu by Maven and download onnxruntime.dll from https://github.com/microsoft/onnxruntime/releases
- ONNX Runtime version: 1.8.0
- CUDA/cuDNN version: CUDA cuda11.03, cuDNN 8.0.2.39

**To Reproduce**
- Describe steps/code to reproduce the behavior.
Here is how I load the model in Java:
```
OrtEnvironment env = OrtEnvironment.getEnvironment();
OrtSession.SessionOptions opts = new OrtSession.SessionOptions();
opts.setExecutionMode(OrtSession.SessionOptions.ExecutionMode.PARALLEL);
opts.addCUDA(0); 
opts.setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT);
logger.info("Loading model from " + modelPath);
OrtSession session = env.createSession(modelPath, opts);
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/86562720/123550059-43f70980-d79e-11eb-9787-9fb807c1a573.png)

Anyone has any hints for this problem? Really appreciate for the help.

**Comment by Craigacp** [comment]
You shouldn't need to download `onnxruntime.dll` separately, it should be packaged into the `onnxruntime_gpu` Maven artifact you downloaded. I can't quite tell if it's actually using the GPU there, is process 8888 your Java test process, or just something else on your machine using the GPU from Java?

Testing against ONNX Runtime in Python on Windows is a good idea. How are you feeding inputs to & retrieving outputs from the model, and what model are you using? To get the best speed out of the Java API you need to use a `java.nio.FloatBuffer` as the input, using a multidimensional array will induce a *lot* of very slow copying which could cause slow inference performance (though it should be equivalently slow between CPU and GPU).

**Comment by MianMianMeow** [comment]
Thanks for your reply~ For the questions you mentioned above,  I did some tests and here are the answers. 

1. You shouldn't need to download onnxruntime.dll separately, it should be packaged into the onnxruntime_gpu Maven artifact you downloaded.
Test 1: Using onnxruntime_gpu Maven artifact only -> still has the same problem.

2. is process 8888 your Java test process?
Yes. The GPU is working for my Java test here.

3. Test on Windows+Python+Onnxruntime
Test 2: GPU-Util is about 76% and inferencing speed is about 65ms / frame, which seems the performances on Windows and Ubuntu with Python+Onnxruntime are the same.

4.  Model, inputs, outputs
Model network: https://github.com/MianMianMeow/testJavaOnnxruntime/blob/main/swimming512.onnx.svg
Input: NodeInfo(name=input,info=TensorInfo(javaType=FLOAT,onnxType=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,shape=[1, 3, 512, 512]))
Output: NodeInfo(name=pts,info=TensorInfo(javaType=FLOAT,onnxType=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,shape=[-1, 7]))
Multidimensional array was used for the input and output.

5. java.nio.FloatBuffer as the input rather than using a multidimensional array 
Test 3: Following _https://github.com/microsoft/onnxruntime/blob/user/dwayner/FixRoiAlign/java/src/test/java/ai/onnxruntime/InferenceTest.java_ and its function _testModelInputBuffer()_ to use **java.nio.FloatBuffer** as the input and output, the inference speed is about 420 ms/frame on CPU and 320 ms/frame on GPU (with the problem of low GPU-Util), which brings a speed up compared to using multidimential array as input and output (multidimential array: about 450ms/frame on CPU, 350ms/frame on GPU).

Based on the tests above, it seems the problem is related to the system environment of Java + onnxruntime_gpu(Maven), but I still cannot figure out the solution.

**Comment by Craigacp** [comment]
The code in `testModelInputBuffer` is better than an array, but still does a few too many copies (as it's designed to test the direct buffer allocation functionality), so there might be further ways to improve that, though I agree it doesn't appear to be the whole issue.

Is it 350ms for the first iteration of inference, or after everything has warmed up some? Would it be possible to show the code from your inference loop?

**Comment by MianMianMeow** [comment]
Wow~Really thanks for your quick reply.
350ms is for the warmed up inference. The first frame inference is much slower.
![image](https://user-images.githubusercontent.com/86562720/123657634-8c2c2f80-d863-11eb-8ff8-7b15aee63c4b.png)

Here's my code for inferencing:
Java, multidimension array (this produce the correct boundingboxes):
```
   // model loading and session create
   OrtEnvironment env = OrtEnvironment.getEnvironment();
   OrtSession.SessionOptions opts = new OrtSession.SessionOptions();
   opts.setExecutionMode(OrtSession.SessionOptions.ExecutionMode.PARALLEL);
   opts.addCUDA(0); 

   opts.setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT);
   logger.info("Loading model from " + modelPath);
   OrtSession session = env.createSession(modelPath, opts);
```

        // inference on one image
        private static Mat processOneImage512(Mat imgBGR, double w, double h, String inputName, OrtEnvironment env, OrtSession 
        session, boolean singleImage) throws OrtException {
        Mat paddedImage = pad2(imgBGR, w,  h);

        Mat processedImage = Dnn.blobFromImage(paddedImage, 1.0/255.0, new Size(512, 512), new Scalar(0, 0, 0), true, false);
        float[][][][] imgArray = convertMatArray3chNoScale(processedImage);
        OnnxTensor input_tensor = OnnxTensor.createTensor(env, imgArray);
        OrtSession.Result output = session.run(Collections.singletonMap(inputName, input_tensor));

        float[][] result = (float[][])output.get(0).getValue();
        // draw boundingboxes on the paddedImage
        List<Rect> rectList = getBoundingBoxesToInputSizeImage512(result);
        Mat resizedPaddedImage = new Mat();
        Imgproc.resize(paddedImage, resizedPaddedImage, new Size(INPUT_SIZE, INPUT_SIZE));
        return draw(resizedPaddedImage,  rectList, singleImage);
    }`

```
// convert image to multidimensional array
private static float[][][][] convertMatArray3chNoScale(Mat img) {
        // img: rgb
        int ch = 3;
        float [][][][] input = new float[1][ch][INPUT_SIZE][INPUT_SIZE];
        for (int c = 0; c < ch; c++) {
            for (int i = 0; i < INPUT_SIZE; i++){
                for (int j = 0; j < INPUT_SIZE; j++){
                    double[] temp = img.get(new int[]{0, c, i, j});
                    input[0][c][j][i] = (float)temp[0];
                }
            }
        }
        return input;
    }
```

Java, FloatBuffer (here may have some problems in dimenstions for converting the image into FloatBuffer so it cannot produce correct boundingboxes. I will correct it later.). TestHelpers is from https://github.com/microsoft/onnxruntime/blob/user/dwayner/FixRoiAlign/java/src/test/java/ai/onnxruntime/TestHelpers.java:
```
// the model loading part is the same as above
private static Mat processOneImage512(Mat imgBGR, double w, double h, String inputName, OrtEnvironment env, OrtSession session, boolean singleImage) throws OrtException {
        Mat paddedImage = pad2(imgBGR, w,  h);

        Mat processedImage = Dnn.blobFromImage(paddedImage, 1.0/255.0, new Size(512, 512), new Scalar(0, 0, 0), true, false);
        float[] imgArray = convertMatArray1chNoScale(processedImage);
        FloatBuffer buffer = FloatBuffer.wrap(imgArray);
        long[] shape = new long[] {1, 3, INPUT_SIZE, INPUT_SIZE};

        OnnxTensor input_tensor = OnnxTensor.createTensor(env, buffer, shape);
        Map<String, OnnxTensor> container = new HashMap<>();
        container.put(inputName, input_tensor);
        float[] resultArray;
        try (OrtSession.Result res = session.run(container)) {
            resultArray = TestHelpers.flattenFloat(res.get(0).getValue());
            OnnxValue.close(container);

        }
        container.clear();
}

private static float[] convertMatArray1chNoScale(Mat img) {
        // img: rgb
        int ch = 3;
        float [] input = new float[ch * INPUT_SIZE * INPUT_SIZE];
        int index = 0;
        for (int c = 0; c < ch; c++) {
            for (int i = 0; i < INPUT_SIZE; i++){
                for (int j = 0; j < INPUT_SIZE; j++){
                    double[] temp = img.get(new int[]{0, c, i, j});
                    input[index] = (float)temp[0];
                    index++;
                }
            }
        }

        return input;
    }
```
Python
```
sess = ort.InferenceSession(onnx_file)
sess.set_providers(['CUDAExecutionProvider'], [{'device_id': 0}])

    while ret:
        cnt += 1
        ret, img = cap.read()
        if cnt % 10 != 0 : continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        org_img = img.copy()
        img = padding2square(img)
        start = time.time()
        onnx_result = sess.run(None, {'input': img})[0]

def padding2square(input):
    H, W = input.shape[0], input.shape[1]
    max_length = max(H, W)
    pad_r = max_length - H
    pad_d = max_length - W
    output = cv2.copyMakeBorder(input, 0, pad_r, 0, pad_d, cv2.BORDER_CONSTANT, value=0)
    output = cv2.resize(output, inres) / 255.
    output = np.array(output, dtype=np.float32)
    output = output.transpose(2, 1, 0)
    output = output[np.newaxis, ...]
    return output
```

**Comment by Craigacp** [comment]
Ok, so I think there is still quite a lot of overhead in how you're copying the data in and out. It looks like there are bulk copies available on OpenCV's `Mat` but I'm not sure if those will dump out the data in the right shape (you can try `img.get(0,0,input)` but I'm not sure what order the bytes are stored in). One quick thing you could do is to allocate the indexing array at the start of the `convertMatArray1chNoScale` function, and then update its values in the for loop as appropriate. Making a fresh array each time is going to trigger a lot of allocations and if it's actually bottoming out in a JNI call in OpenCV, I'm not sure that the escape analysis will manage to elide the allocation.

On the outbound side, the code in `TestHelpers.flattenFloat` is slow & recursive which is definitely not what you want in a tight loop. It's in the tests because it's correct and works across a wide variety of shapes so it's useful in the unit tests, but it's definitely not fast. You can copy the output to a `FloatBuffer` using `((OnnxTensor) res.get(0)).getFloatBuffer()` and that should be much faster.

One final element of the baseline, how fast is the python code you posted running on the CPU?

**Comment by MianMianMeow** [comment]
@Craigacp 
### Problem solved.

The problem of low GPU_Util is exactly caused by the nested loop through every element of a Mat to generate an one-dimensional array as the input,  as you mentioned above. Also following your suggestions, I used `img.get(0,0,input) `to generate the array without the multidimentional array or nested loop. Here's my code for input data generation:
```
private static Mat processOneImage512(Mat imgBGR, double w, double h, String inputName, OrtEnvironment env, OrtSession session, boolean singleImage) throws OrtException {
        Mat paddedImage = pad2(imgBGR, w,  h);
        Mat processedImage = Dnn.blobFromImage(paddedImage, 1.0/255.0, new Size(512, 512), new Scalar(0.0, 0.0, 0.0), true, false, CvType.CV_32F);

        float[] imgArray = new float[512 * 512 * 3];
        int[] idx = {0, 0, 0, 0};

        processedImage.get(idx, imgArray); // processedImage: CvType.depth(t) == 5, CV_32F, processedImage.dims() = 4

        FloatBuffer buffer = FloatBuffer.wrap(imgArray);
        long[] shape = new long[] {1, 3, INPUT_SIZE, INPUT_SIZE};

        OnnxTensor input_tensor = OnnxTensor.createTensor(env, buffer, shape);
        float[][] result;
        try (OrtSession.Result res = session.run(Collections.singletonMap(inputName, input_tensor))) {
            result = (float[][])res.get(0).getValue();
        }

    }
```
I will improve the output by copying it to a FloatBuffer later.
For your reference, currently the inferencing speeds and GPU_Util on Windows+Java+Onnxrumtime,  Windows+Python+Onnxrumtime, Ubuntu+Python+Onnxrumtime seem no big difference : CPU 145ms/frame, GPU(CUDA) 65ms/frame. GPU_Util for Java is about 80%, and is about 75% for Python.

Thanks again and have a nice day :)

**Comment by Craigacp** [comment]
Excellent, I'm glad that resolved your issue.
